### ISSUE TITLE
NGB cannot register .bed.gz files

### ISSUE THREAD

**Issue by NickPanyushev** [epam/NGB#101]
As a user I'd be very pleasured if .bed files could be registered from the .gz-compressed archive

When trying to register bed.gz archive - the following error is encountered:
12:31:09.952 [main] ERROR com.epam.ngb.cli.manager.command.handler.http.FileRegistrationHandler - Failed to register files: path/to/file/A549_GRCh38.DNAse1_peaks.bed.gz.

After the gunzip decompression this file has been successfully registered.

I've tested the 3405045 commit code

**Comment by sidoruka** [comment]
Could you please attach example file that can be used to reproduce that?

**Comment by NickPanyushev** [comment]
[A549_GRCh38_H3K36me3_peaks.bed.gz](https://github.com/epam/NGB/files/1398160/A549_GRCh38_H3K36me3_peaks.bed.gz)

**Comment by sidoruka** [comment]
This file appears to be a "gzipped" file. While NGB accepts "bgzip" format. "bgzip" tools is available as a part of "samtools" package.
But I see that [CLI documentation](https://github.com/epam/NGB/blob/master/docs/md/cli/command-reference.md#register-file) does not explicitly specify this requirement, that shall be fixed

NB: you can also use [CLI "sort" command](https://github.com/epam/NGB/blob/master/docs/md/cli/command-reference.md#sort-feature-file) to to do bgzipping

**Comment by sidoruka** [comment]
Fixed docs in 07ed5dd

**Comment by NickPanyushev** [comment]
Thank you very much for the detailed answer and explanation!
