### ISSUE TITLE
[Target Idenitification] Saving Identification

### ISSUE THREAD

**Issue by mzueva** [epam/NGB#1031]
**Background**
Let's introduce an option to save identification settings

**Approach**
A new object shall be introduced to save target identification with the following fields:

- id
- created date
- name
- owner
- target id
- genes of interest ids
- translation gene ids

The following API shall be provided:
- create/edit/delete new identification
- get list of all identifications with paging and filters (by name, owner, target id, gene id)
- get list of all identification by target (without paging)

From GUI prospective:
- Add save button to identification page, by clicking this button user may enter name for save identification and click `Save` or `Cancel` buttons
- In the list of Targets a new button shall be added near the `launch` button to browse and open saved identifications for the target. Button shall be displayed only if target has saved identifications. When user opens the list of saved identifications a new pop-up window shall be shown. For each identification we show: name, genes of interest, translational genes and buttons delete/open. If user modifies any of the fields `save` button shall be active for click.

**Comment by maryvictol** [comment]
@AlfiyaRF 

**Bug:**
Identifications tab opens with a disabled **Save** button if the previous Identification was saved and the page wasn't refreshed.

**Comment by mzueva** [comment]
> 
> **Bug:** Identifications tab opens with a disabled **Save** button if the previous Identification was saved and the page wasn't refreshed.

@maryvictol shall be fixed

---
Verified as fixed
