### ISSUE TITLE
[Comparative Genomics] Alignment of sequences gives error at case of large number sequences.

### ISSUE THREAD

**Issue by maryvictol** [epam/NGB#1033]
Comparative Genomics: Alignment of sequences gives error at case of large number sequences.

**To Reproduce**
1. Go to **Targets**
2. Identify  _BRCA Complex_ with
Interest: BRCA1 (Homo sapiens)
Translational: BRCA1 (Canis lupus familiaris)
3. In the **Comparative Genomics** specify
Target: BRCA1 (Homo sapiens) 
Query: BRCA1 (Canis lupus familiaris)
Select any proteins for both targets and click **Align**
5. See error `Sequences are not aligned yet.`

**Expected results:**
Alignment of sequences gives correct result.

**Comment by mzueva** [comment]
@maryvictol shall be fixed

**Comment by maryvictol** [comment]
Verified as fixed. Works correctly
