### ISSUE TITLE
[Target Identification] The contents of table in the export file of  Structure Local files don't correspond to the UI table

### ISSUE THREAD

**Issue by maryvictol** [epam/NGB#1039]
[Target Identification] The contents of the columns in the export file of  Structure Local files don't correspond to the UI table.

**To Reproduce**
1. Go to **Targets**
2. Identify  _KRAS - KRAS proto-oncogene_ with
Interest: KRAS (Homo Sapiens)
Translational: KRAS (Canis lupus familiaris)
3. In the **Structure** select Source _Local files_
4. Click **Export** button. Compare export file with UI table.
![image](https://github.com/epam/NGB/assets/47791878/613e19a5-0cfa-4026-8069-45c48fe2a0ca)

**Comment by mzueva** [comment]
@maryvictol shall be fixed

**Comment by maryvictol** [comment]
Verified as fixed. Works correctly.
