### ISSUE TITLE
Filters work incorrectly in the Targets table

### ISSUE THREAD

**Issue by maryvictol** [epam/NGB#1041]
Filters work incorrectly in the **Targets** table

1. Filters by **Name** and **Owner** columns don't work
2. _Genes_ column: checkboxes for values with comma can be selected but not marked
![image](https://github.com/epam/NGB/assets/47791878/97514596-416a-434b-93c6-dee8e8eafc3b)

3. _Diseases_ column is filtered by the occurrence of the value selected in the drop-down, not by a match.  
![image](https://github.com/epam/NGB/assets/47791878/5f1d7fc8-4018-4cbc-a76f-5e73dc5b3793)

4. _Specieses_ column: list of existing specieses contains names that differ only by case. The same problem occurs for _Genes_ column
![image](https://github.com/epam/NGB/assets/47791878/3a1a696b-5d1e-493c-aaa4-2d0fc2a35bcf)

**Comment by mzueva** [comment]
@maryvictol point 3 is fixed

**Comment by mzueva** [comment]
@maryvictol all issues shall be fixed

**Comment by maryvictol** [comment]
Verified as fixed
