### ISSUE TITLE
[Target Identification] Allow to launch target identification "ad hoc"

### ISSUE THREAD

**Issue by mzueva** [epam/NGB#1059]
**Background**
At the moment in order to launch an identification user needs to create a target at first and then launch identification. For some cases it would be helpful to allow to launch identification for a target without registration, just select a gene and open report.

**Approach**
User shall be able to open identification report for a target from disease panel.
TBD

**Comment by maryvictol** [comment]
@mzueva 
**Bug:**
Export to Excel, csv: **Target** column is empty in the _Associated Diseases_, _Known Drugs_, _Sequences_ tables.
