### ISSUE TITLE
[Parasite Targets] Therapeutic Target Database integration

### ISSUE THREAD

**Issue by mzueva** [epam/NGB#1130]
**Background**
NGB shall support fetching associated drugs and diseases data from TTD for parasite targets. Assuming that it isn't possible to find data for parasite genes by name or gene id we need to fetch related data matching targets by protein sequences

**Implementation**
API methods to get drugs and diseases for a target shall support new database - TTD. Search shall be performed over data imported into internal storage and consider two types of matches: by gene id and by sequence match.

**Comment by okolesn** [comment]
Drug Table columns:

- Target
- Drug
- Company
- Type
- Therapeutic Class
- InChI
- InChIKey
- Canonical SMILES
- Status
- Compound Class
