### ISSUE TITLE
Update AWS SDK to support EKS Pod Identities

### ISSUE THREAD

**Issue by nikode1** [epam/NGB#1230]
**Background**
The current version of the AWS SDK used in this project does not support AWS EKS Pod Identity as an authentication method. Support for EKS Pod Identity was introduced in version 1.12.746 (per [aws/aws-sdk-java#3062](https://github.com/aws/aws-sdk-java/issues/3062#issuecomment-2192771284)) and provides several advantages over other authentication methods.

**Approach**
Update the AWS SDK to version 1.12.746.

**Other options**
Any later version can be used, provided there are no compatibility concerns.

**Comment by mzueva** [comment]
@nikode1 We updated aws sdk version to 1.12.746, please find binaries here: https://ngb-oss-builds.s3.amazonaws.com/web/index.html?prefix=public/builds/release/2.7.1/2.7.1.4372/

**Comment by nikode1** [comment]
Verified with pod identities - everything works as expected. Thanks!
