### ISSUE TITLE
Support window.opener in JS API

### ISSUE THREAD

**Issue by vladimirbykovepam** [epam/NGB#125]
Would be great if NGB [JS API](https://github.com/epam/NGB/blob/develop/client/client/app/app.controller.js#L152) has support of [window.opener](https://developer.mozilla.org/en-US/docs/Web/API/Window/opener) for ability to communicate with window opened in new tab

**Comment by sidoruka** [comment]
PR merged into develop.
Feel free to reopen the issue if any more changes are required
