### ISSUE TITLE
Unable to load files via the URL

### ISSUE THREAD

**Issue by NickPanyushev** [epam/NGB#128]
After the testing of the https://github.com/epam/NGB/pull/122 pull request code, I occasionally found out this issue. After you paste valid links to data and index into the "Open from URL" form, NGB does not enable load button and returns the warning "You must enter file path"

**Comment by sidoruka** [comment]
@NickPanyushev , does that path contains any query string parameters? Could you please provide an example URL that does not work for you?

**Comment by sidoruka** [comment]
Not a bug
