### ISSUE TITLE
Display full variation location and change in Variation info

### ISSUE THREAD

**Issue by GennadiyZakharov** [epam/NGB#136]
At the moment, variation detailed information contains only variation position in "Location" field. There is no way to copy full variation info to clipboard. Also it is located below "Genes" field, which is not easy to find.
It would be better to have full variation description in detailed info.

I suggest implement variation description field, which should display detailed variation information: chromosome, position and variation specification. For example: chr1 : 95709821  T->C

**Comment by sidoruka** [comment]
@ekoltsova, could look into this once you have time?
