### ISSUE TITLE
Registering bam files with very high coverage

### ISSUE THREAD

**Issue by lloonngg** [epam/NGB#156]
I have added bam files of gigabyte size and with 200-400X average target coverage with no issue.  However, attempting to register a much smaller 140MB bam file with very high target coverage (up to 100,000X or more) I run into heap space and memory issues:

 ERROR com.epam.ngb.cli.manager.command.handler.http.FileRegistrationHandler - Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: GC overhead limit exceeded''

Is this anticipated?  Can NGB handle/support very high coverage bam files?

Long

**Comment by sidoruka** [comment]
Hello @lloonngg , we've tested performance using RNA-seq datasets with up to 700k coverage. 

Don't have this dataset in the public access at the moment, but here is a bit simplier example with ~20k coverage, it loads quite fine: http://ngb.opensource.epam.com/catgenome/navigate?alias=20kRNA 
Can you try this link? Does it work for you?
Having 100k+ will result in a more load time but shall not throw heap errors as all alignments are read in buffered fashion and shall never take all the memory.

Could you please clarify:
1. Which version (commit or tag) you are using?
2. What are the startup arguments for the NGB?

**Comment by lloonngg** [comment]
I'm using the docker container, version:  2.5.1-release.  I just tried again and it appears to be working.  I most likely made a mistake with copying over the bai file from our NAS.  It appears to be working for a very high coverage (>100,000x) bam of 3-5GB total size.  Thanks for your help.

**Comment by sidoruka** [comment]
Thanks for clarifying. I'll close this issue as it seems that aproblem is solved.
Please feel free to reopen or create new if any other issue uncovers.
