### ISSUE TITLE
Persisting H2 database and contents while running NGB in Docker container

### ISSUE THREAD

**Issue by lloonngg** [epam/NGB#2]
I just want to say that NGB is a great genomics browser.  I was able to quickly deploy the application as a docker container.  

This is not so much of an unresolved issue but rather a proposed solution to an issue I encountered when deploying NGB in a docker container.  One thing that was not clear from the documentation is how to persist data (reference, gene, bed, etc. registrations and datasets) between container sessions.

I was able to come up with a solution that seems to work.  Essentially, both the H2 and contents folder under /opt/catgenome have to be locally stored on the host and mounted as volumes when initally using "docker run."  Here is the command I used:

`docker run --privileged -p 8080:8080 -d --name ngb -v /host/ngs:/ngs -v /host/H2:/opt/catgenome/H2 -v /host/contents:/opt/catgenome/contents lifescience/ngb`

So in our setup:

/host/ngs is where the bam and bai files live.  We have it mounted via sshfs which is why "[--privileged](https://forums.docker.com/t/mounting-a-sshfs-folder-and-share-it-with-host/7528)" is needed in the docker command.

/host/H2 is where the NGB database will be persisted on the host.

/host/contents is where the NGB registered files will be persisted on the host.

After stopping the docker container or a host reboot, launching "docker start ngb" will load up from where it left off with persistent contents and datasets.

Hopefully this helps others who want to deploy as a docker container.

**Comment by sidoruka** [comment]
@lloonngg , thanks a lot for pointing this out! This is really valuable comment and we will incorporate this instruction into the `docker` installation guide with the next update.
I will keep this issue open until `release 2.5`.

We will appreciate your further comments.

**Comment by sidoruka** [comment]
Closing this, as description was added to [Docker manual](https://github.com/epam/NGB/blob/master/docs/md/installation/docker.md#persisting-registered-data) in f4d2deae9e7d83e9c6f32a53190ce99e46d9191f

Once more: thanks for this investigation!
