### ISSUE TITLE
Support registration of S3 files

### ISSUE THREAD

**Issue by mzueva** [epam/NGB#214]
### Add support for registration of S3 files to server API and NGB CLI

NGB shall support registration of S3 files for the following supported formats: BAM, VCF, GENE (GFF/GTF), BED, BedGraph, WIG, SEG.

#### Authorization
NGB shall expose AWS [Default Credential Provider Chain](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html) for S3 access  

#### Implementation details
1. NGB Server API shall support registration of files with type "S3". File and index existence shall be checked on file registration. Index file is required for S3 resources. Creation of Lucene index for S3 sources (VCF, GENE, BED) shall be supported.
2. NGB CLI shall support registration of S3 files. File type (S3/Local) shall be determined by path: S3 resources shall be registered using "s3://" scheme.

**Comment by sidoruka** [comment]
@SilinPavel I'm sure that this feature is implemented, am I right?

**Comment by SilinPavel** [comment]
@sidoruka Yes that's right. There is could be some troubles with WIG registration because of creation of a index file. But after implementation of WIG file reading from S3 it also should be fine. So @vpolyakov88  Registration for BAM VCF BED GENE SEG files can be tested.

**Comment by sidoruka** [comment]
Ok, closing this one. 
Once other NGS files we'll be implemented (tracked in #215) and something does not work (probably no reason for that) - we can always reopen.
