### ISSUE TITLE
Support reading of S3 files using AWS Java SDK

### ISSUE THREAD

**Issue by mzueva** [epam/NGB#215]
### Add support for reading S3 resources 

NGB shall support reading of S3 files for both scenarios: registered files and non registered (opened via url) files. Supported formats: BAM, VCF, GENE (GFF/GTF), BED, BedGraph, WIG, SEG.

#### Authorization
NGB shall expose AWS Default Credential Provider Chain for S3 access

#### Implementation details
1. Overall approach to reading S3 resources shall be reused from non-parallel version of [htsjdk-s3-plugin](https://github.com/epam/htsjdk-s3-plugin)
2. For BAM Files provide S3 implementation of **SamInputResource**
3. For Feature files (VCF, BED, GENE, SEG, BedGraph) provide implementation of **ISeekableStreamFactory** with support of S3 paths
4. For WIG files - check supported input resources in currently used library **org.jetbrains.bio.big**

**Comment by sidoruka** [comment]
# S3 support for specific filetypes

*Updated on Dec-13, 2018*
*`Benchmark` field shows comparison of the data retrieval of 100b range for S3 and local FS*

| Filetype | S3 supported | Benchmark | Comment |
| ------------- | ------------- | ------------- | ------------- |
| BAM | Yes | ToDo | |
| VCF | Yes | ToDo | |
| BED | No | ToDo | |
| GENE (gtf/gff3) | No | ToDo | |
| WIG | No | ToDo | Requires custom implementation, as it is not natively supported by `htsjdk` |
| BedGraph | No | ToDo | |
| SEG | No | ToDo | |

@mzueva @SilinPavel  and all, please ping me if something is implemented and shall be updated in the table able.

**Comment by mzueva** [comment]
Regarding WIG file support for S3 sources: аccording to release notes, latest versions of [big library](https://github.com/JetBrains-Research/big) should support 

> New buffer factories for files/urls reading based on hts-jdk SeekableStream

This could be an option for us to add integration with S3 for WIG files. @tcibinan Please check whether we could integrate latest version of [big library](https://github.com/JetBrains-Research/big) with our custom `S3SeekableStreamFactory` and `SeekableS3Stream` classes. Code for reading WIG files is located in `WigProcessor` class.
