### ISSUE TITLE
RBAC: Support permissions management in CLI

### ISSUE THREAD

**Issue by sidoruka** [epam/NGB#216]
While RBAC Server API is in place for development and GUI management is being implemented, we shall also allow admins to use CLI for manual configuration or automation purposes.

Actions to be supported by CLI:
* Grant
* Deny
* Unset (remove any permissions from the object, to inherit them from the parent)

Permissions to be supported by CLI:
* Read
* Write

Identity types to be supported by CLI:
* User
* Group

NGB Objects to be supported by CLI:
* File
* Dataset

Keeping this in mind - the following command signature may be considered
```
ngb chmod  [mod] \
    --datasets [DATASET_COMMA_SEPARATED_LIST] \
    --files [FILES_COMMA_SEPARATED_LIST] \
    --users [USER_NAMES_COMMA_SEPARATED_LIST] \
    --groups [GROUPS_NAMES_COMMA_SEPARATED_LIST]
```

* `[mod]` parameter is mandatory. This parameter shall fit the following format: `[Action type][Permission]

To set the action type, the following prefixes can be used:
    * `+` - to grant permissions
    * `-` - to deny permissions
    * `!` - to unset permissions

To set the permission, the following suffixes can be used:
    * `r` - read permission
    * `w` - read permission

* One of or both `--datasets`/`--files` shall be specified
* One of or both `--users`/`--groups` shall be specified
* Operation is NOT recursive, applied only to the specified `--datasets`/`--files`

Examples:
```
# Grant read access to "Dataset1" and "Dataset2" for `user1` and group `ngs_users`
ngb chmod +r --datasets "Dataset1,Dataset2" --users "user1" --groups "ngs_users"
```

@mzueva , @SilinPavel any concerns on the proposal?

**Comment by SilinPavel** [comment]
This feature are implemented now and can be find in **f_cli_grant_permissions** branch, so @vpolyakov88, it's can be tested! @sidoruka [mode] parameter template was changed to [Permission][Action type], as discussed.

**Comment by SilinPavel** [comment]
Just leaving comment about `chmod` command here,

# Assign/Remove permissions on a file or a datasets  to specific user/group
~~~
ngb chmod  [mod] \
    --datasets [DATASET_COMMA_SEPARATED_LIST] \
    --files [FILES_COMMA_SEPARATED_LIST] \
    --users [USER_NAMES_COMMA_SEPARATED_LIST] \
    --groups [GROUPS_NAMES_COMMA_SEPARATED_LIST]

// Arguments:
// [mod] contains two parts: [Permission] [Action type]
// `+` - to grant permissions
// `-` - to deny permissions
// `!` - to remove all already assigned permissions
// r - read permission
// w - write permission

// Option:
// -u (--users)           Comma-separated list of user names. This users will have specified permissions for the specified files and datasets
// -gr (--groups)         Comma-separated list of groups. This groups will have specified permissions for the specified files and datasets
// -fl (--files)          Comma-separated list of files. 
// -ds (--datasets)       Comma-separated list of datasets. 
~~~

Description:
`Assing/Remove` permission on specific `file (files)` and `dataset (datasets)` for the specified `user (users)` and `group (groups)`

Examples:
~~~
# Grant read access to "Dataset1" and "Dataset2" for `user1` and group `ngs_users`
ngb chmod +r --datasets "Dataset1,Dataset2" --users "user1" --groups "ngs_users"
~~~

~~~
# Removing permission for "Dataset1" and "Dataset2" from `user1` and group `ngs_users`
ngb chmod ! --datasets "Dataset1,Dataset2" --users "user1" --groups "ngs_users"
~~~

**Comment by vpolyakov88** [comment]
tested
