### ISSUE TITLE
Support registration of SwiftStack files

### ISSUE THREAD

**Issue by sidoruka** [epam/NGB#222]
@mzueva , please fill in the details of this feature as for #214

**Comment by mzueva** [comment]
### SwiftStack integration

#### Overall approach
SwiftStack provides support for S3 API: https://www.swiftstack.com/docs/admin/middleware/s3_middleware.html. 
SwiftStack provides values for the following properties, used for AWS S3 API access:

- S3 API URL = aws_endpoint_url
- S3 Region = aws_region
- S3 Account Secret Key = aws_secret_access_key 
- UserName = aws_access_key_id

Using these setting we can reuse all code for S3 resources for accessing SwiftStack data.

#### Implementation details

1. Add support for SwiftStack files registration with scheme `sws`. E.g. file with path `project/sample1.bam` in container `ngs-data` shall be accessed via uri: `sws://ngs-data/project/sample1.bam`
2. Add four new properties to NGB configuration (catgenome.properties):
- swift.stack.endpoint.url
- swift.stack.region
- swift.stack.secret.key
- swift.stack.secret.id
3. `S3Client` shall be made nonstatic, instead we should initialize two clients: `S3Client` (initialized using AWS default credentials chain) & `SwiftStackClient` (initialized using properties form point 2)
4. While reading S3 and SwiftStack resources corresponding client shall be selected according to file scheme or `BiologicalDataItemResourceType`
