### ISSUE TITLE
Non admin user can change permissions by NGB CLI.

### ISSUE THREAD

**Issue by vpolyakov88** [epam/NGB#237]
#216 
1. Login as admin in CLI.
2. Create dataset.
3. Open NGB UI and login as admin.
4. Find created dataset and click on dataset RMB.
5. Set non admin user as owner.
6. Login in CLI by this user.
7. change dataset permissions by CLI command ngb chmod.

exp.: when non admin user try ti change any permissions error shall be displayed.
act.: non admin user can change permissions on dataset.

**Comment by SilinPavel** [comment]
@vpolyakov88 this bug was fixed in  3ba4391, please check!

**Comment by vpolyakov88** [comment]
tested
