### ISSUE TITLE
Dataset isn't displayed if admin grant read by CLI and then deny write.

### ISSUE THREAD

**Issue by vpolyakov88** [epam/NGB#239]
#216 
1. Login in NGB CLI as admin.
2. Grant read permissions on dataset for user by command `ngb chmod r+ --datasets "{dataset}" --users "{username}"`
3. Deny write permissions on the same dataset by command `ngb chmod w- --datasets "{dataset}" --users "{username}"`
4. Login in NGB UI as admin.
5. Click RMB on dataset.
6. Click on "MANAGE PERMISSIONS"
7. Click on username.

exp.: checkboxes  for read permission allow and for write permission deny are enabled.
act.: ceckbox is enabled only for write permission deny.

**Comment by SilinPavel** [comment]
commit  737aea2 contains fix for this bug. Please check!

**Comment by vpolyakov88** [comment]
tested
