### ISSUE TITLE
Admin can't force delete group if in used in datasets settings. And see unexpected error.

### ISSUE THREAD

**Issue by vpolyakov88** [epam/NGB#243]
#219 

1. Create group
2. Add user in group
3. Navigate to any dataset, RMB click and click on "MANAGE PERMISSIONS".
4. Add group on "Manage permissions" pop-up.
5. Try to remove group by UI.
6. Try to remove group by CLI.

exp.: handled exception with text "Group used in dataset {dataset_name}. Force delete role?" is displayed if admin try to delete group by UI. On pop-up also displayed buttons "Yes", "No". If user try to delete group by CLI handled exception with text "Group used in dataset {dataset_name}. Use --force| -f for froce delete this group."
act.: No any message on UI. Message "Your operation has been aborted due to data access is denied." is displayed on CLI.

**Comment by SilinPavel** [comment]
@vpolyakov88 fixed and can be checked. But please note that group would be deleted without any additional message, I believe that if admin wants to delete a group he understand that all permissions connected with this group will be deleted too.

**Comment by sidoruka** [comment]
> But please note that group would be deleted without any additional message
Agree with that

**Comment by vpolyakov88** [comment]
tested
