### ISSUE TITLE
Add NGB CLI command for remove users from group.

### ISSUE THREAD

**Issue by vpolyakov88** [epam/NGB#244]
#219 

Now admin can't remove users from existing group by NGB CLI. Please add CLI command for remove users from existing group.

**Comment by SilinPavel** [comment]
@vpolyakov88 This issue is implemented now ( 73992c4 ),please feel free to check!

**Comment by SilinPavel** [comment]
And here is the description of this command for the new documentation
 
# Remove users from an existing group
```
ngb rem_group|rmgrp [<Group name>] [options]

//Options:
//-u (users)          List of users to be deleted from a group
//-t (--table)          Print result as a human-readable table
//-j (--json)           Print result as a JSON string
```

*Description*
Removes a single user or a list of users (comma-separated list, specified by `-u (--users)` option) from the group, specified by `<Group name>` parameter.

*Example*
```
//Delete "pavel_silin@epam.com" and "aleksandr_sidoruk@epam.com" users from the "Developers" group
ngb rem_group Developers -u pavel_silin@epam.com,aleksandr_sidoruk@epam.com
```

**Comment by vpolyakov88** [comment]
tested
