### ISSUE TITLE
User management pop-up is closing if admin create group and add user.

### ISSUE THREAD

**Issue by vpolyakov88** [epam/NGB#256]
#220 

1. Login as admin.
2. Open "User management".
3. Navigate to "Groups" tab.
4. Click on "Create" button.
5. Enter valid group name.
6. Click on "Select user to add" combo-box and click "Add" button.
7. Click on "Create" button.

exp.: "User management" pop-up is not closing.
act.: "User management" pop-up is closing.

**Comment by rodichenko** [comment]
@vpolyakov88 fixed, re-check this issue please.

**Comment by vpolyakov88** [comment]
tested
