### ISSUE TITLE
SAML session expiration is not handled

### ISSUE THREAD

**Issue by sidoruka** [epam/NGB#263]
Currently if user is idle for ~30 minutes (e.g. didn't close a browser window) - SAML session expires.
Once user is back and tries to perform any action using the GUI - nothing happens. Under the hood - `HTTP 401` is returned by the server and client just logs it.

We shall consider two options If a session is expired:
1. User is presented with a dialog saying `Your session is expired. Login back`. Where `Login back` is a hyperlink, clicking it - shall refresh the page and login back
2. User is automatically redirected to the root page, which shall reload the page and force login

Both options shall be implemented, which one to use - shall be controlled by the server settings. Let's introduce a parameter (e.g. `session.expiration.bahavior`) with two possible values: `CONFIRM` for (1) and `AUTO` for (2)

**Comment by SilinPavel** [comment]
Implemented on the server side

**Comment by rodichenko** [comment]
Both options (auto-redirecting & displaying the dialog) are implemented on the client side.
