### ISSUE TITLE
Show tracks in Expanded view by default or make this choice configurable.

### ISSUE THREAD

**Issue by Dmitrii-Romanov** [epam/NGB#277]

**Comment by rodichenko** [comment]
@Dmitrii-Romanov user can configure this choices:
1. Open settings dialog;
2. Navigate to `Customize` tab;
3. Scroll to `BAM`, `GENE` or `VCF` sections (those sections have 'Expanded/Collapsed' options) and set default behavior.
![expand_collapse](https://user-images.githubusercontent.com/5070496/55973667-c2833180-5c8e-11e9-951a-5a3a59d119a1.png)

**Comment by Dmitrii-Romanov** [comment]
@rodichenko thanks a lot.
