### ISSUE TITLE
NGB can't fetch information from UniProt 

### ISSUE THREAD

**Issue by Dmitrii-Romanov** [epam/NGB#283]
Click on a gene, then "Show info", UNIPROT.
Following message appears:
**No Data Available
Unexpected HTTP status: 301 Moved Permanently for URL http://www.uniprot.org/uniprot/?query=ENSG00000229102&format=xml**

![image](https://user-images.githubusercontent.com/30798676/56021921-4a128400-5d13-11e9-8e06-d1acf2a7c462.png)

**Comment by sidoruka** [comment]
Closing as a duplicate of #371
