### ISSUE TITLE
NGB  JWT Authentication

### ISSUE THREAD

**Issue by Sanwel** [epam/NGB#285]
Inability to use jwt authentication ngb
---
Requirements:
NGB version: dev/2.6.0.1326.1
Google Chrome 73.0.3683.103

Configs was wrote according to documentation 
http://ngb.opensource.epam.com/distr/dev/2.6.0.1326.1/docs/

We have current config at catgenome.properties: 
---
path.style.access.enabled=true
file.browsing.allowed=true
ngs.data.root.path=/ngs/
jwt.security.enable=true
jwt.key.public=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDFLWz3GPn5cs/+a3eO/s8gwzhoD/Tjy8/VUXZtrIAF3H3DxAy3y1M6bd0ZZ3VmZfHhumaSkLSw3V2lzDHIl/7BFfXK7iXvg0FICE6fothQZvQNhEAi3EjOtVcf7BofntkeMRRTouXjh8RHeLmv+HXT73WdThiac0h+Dfaeu6BkcQIDAQAB

and have requests with cookies:
---
NgbToken="some valid token"; HttpAuthorization="other valid token"

In this case we have, error page like on this screen with 401 errors: 
---
![image](https://user-images.githubusercontent.com/42137467/57216784-87f48680-6ff9-11e9-800b-3e8bfa737564.png)

To solve that problem I've tried to use apache as proxy before ngb, with following config, to move tokent from cookie to Authorization header
---
apache.config:
<VirtualHost *:80>
ProxyRequests On
ProxyVia On
<Location /catgenome/>
        SetEnvIf cookie "HttpAuthorization=([\w\.\-]*)" MyCookieValue=$1
        RequestHeader set Authorization "Bearer %{MyCookieValue}e"
        AllowOverride None
        ProxyPass "http://localhost:8080/catgenome/"
<\/Location>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
<\/VirtualHost>

As result I got the following problem:
---
![image](https://user-images.githubusercontent.com/42137467/57218331-b4aa9d00-6ffd-11e9-9f5e-f012135a0885.png)

Please help me, maybe I made a mistake somewhere with the settings, or how it can be fixed in other way?

**Comment by sidoruka** [comment]
@Sanwel you are correct, there is an issue with cookie value parsing.
Shall be fixed by c9f8b6d 
Now `HttpAuthorization="other valid token"` cookie shall be sufficient to pass the authentication

* Docker distribution: `lifescience/ngb:2.6.0.1329.1-dev`
* Jar/WAR/CLI distributions: [dev/2.6.0.1329.1](http://ngb.opensource.epam.com/distr/dev/2.6.0.1329.1/)

Could you please double check and report back?

**Comment by Sanwel** [comment]
@sidoruka, yep it fixed the problem with cookie thank you, but now ngb have same problem as described above like with apache proxy, all requests to  /catgenome/restapi/* failed with 500 error code.

**Comment by sidoruka** [comment]
@Sanwel, please give it another try:

* Docker distribution: lifescience/ngb:2.6.0.1330.1-dev
* Jar/WAR/CLI distributions: [dev/2.6.0.1330.1](http://ngb.opensource.epam.com/distr/dev/2.6.0.1330.1/)

The JWT you were using, was incompatible. NGB was expecting `user_id` field as a `long`, while it was a `string`. This is fixed via b6bd643

**Comment by Sanwel** [comment]
@sidoruka, thank you, now problem with JWT token, are solved, but we have some troubles with access to s3 .bam files, while .vcf files are displayed correct, and give normal response, requests to .bam files  return this error :
{"payload":{"blocks":[]},"status":"ERROR","message":"com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Swift Stack client is not configured!"}

**Comment by sidoruka** [comment]
> but we have some troubles with access to s3 .bam files

@Sanwel please consider creating separate issues for separate problems.
I've created #286 for this one


> thank you, now problem with JWT token, are solved

Great, closing this one
