### ISSUE TITLE
Unable to load bam files from the S3 storage

### ISSUE THREAD

**Issue by sidoruka** [epam/NGB#286]
Reported by @Sanwel via #285 

We have some troubles with access to s3 .bam files, while .vcf files are displayed correct, and give normal response, requests to .bam files return this error :
{"payload":{"blocks":[]},"status":"ERROR","message":"com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Swift Stack client is not configured!"}

**Comment by sidoruka** [comment]
A couple of details on this issue:
1. AWS credentials are set using EC2 instance role (not account id/secret are available)
2. BAM/VCF are not registered in the NGB. Instead, they are opened using `Open by URL` option (before native AWS support this was working using `signed-urls`, may be this is causing an issue)
3. NGB config has a minimal number of options set:
```
file.browsing.allowed=true
ngs.data.root.path=/ngs/
jwt.security.enable=true
jwt.key.public=<value>
```

**Comment by sidoruka** [comment]
@Sanwel, please confirm that the above comment https://github.com/epam/NGB/issues/286#issuecomment-496155560 is correct

**Comment by Sanwel** [comment]
@sidoruka, yes all is correct!

**Comment by sidoruka** [comment]
@Sanwel please try the fixed version:
* Docker distribution: `lifescience/ngb:2.6.0.1334.1-dev`
* Jar/WAR/CLI distributions: [dev/2.6.0.1334.1](http://ngb.opensource.epam.com/distr/dev/2.6.0.1334.1/)

**Comment by Sanwel** [comment]
@sidoruka thank you, for hotfix. All works, according to expectation!

**Comment by sidoruka** [comment]
Nice, thanks for checking out.
