### ISSUE TITLE
NGB remote postgres DB

### ISSUE THREAD

**Issue by Sanwel** [epam/NGB#290]
Dear NGB team,

Is there any option use remote postgres DB for NGB?
Don’t find any information about that in documentation.

With config which I attach bellow, NGB try to create DB with H2 driver and fail with syntax error. (NGB version 2.6.0.1317.1-dev )

catgenome.properties:
file.browsing.allowed=true
ngs.data.root.path=/ngs/
database.max.pool.size=10
database.username=catgenome
database.password=catgenome
database.initial.pool.size=5
database.driver.class=org.postgresql.Driver
database.jdbc.url=jdbc:postgresql://ngb-db.d2:5432/ngb_test

SQL State  : 42601
Error Code : 0
Message    : ERROR: syntax error at or near ")"
  Position: 356
Location   : database/catgenome/h2/v2016.11.21_17.58__Database_create_script.sql (/opt/ngb/file:/opt/ngb/catgenome.jar!/BOOT-INF/classes!/database/catgenome/h2/v2016.11.21_17.58__Database_create_script.sql)
Line       : 103
Statement  : CREATE TABLE IF NOT EXISTS CATGENOME.VCF_SAMPLE (
  VCF_SAMPLE_ID  BIGINT         NOT NULL,
  VCF_ID         BIGINT         NOT NULL,
  SAMPLE_NAME    VARCHAR(250)   NOT NULL,
  ORDER_INDEX    INTEGER,
  CONSTRAINT vcf_sample_id_pkey PRIMARY KEY (VCF_SAMPLE_ID),
  CONSTRAINT vcf_sample_vcf_id_fkey FOREIGN KEY (VCF_ID) REFERENCES CATGENOME.VCF (VCF_ID),
)
Is there any options to avoid it? Will it help if we rebuild jar with -Pprofile=postgres option?

**Comment by mzueva** [comment]
@Sanwel In order to run NGB with PostgreSQL DB you need to build it with property: 
`-Pdatabase=postgres`. The command to build executable jar may look the following:
`./gradlew buildJar -x test -PnoTest -Pdatabase=postgres`

**Comment by Sanwel** [comment]
@mzueva thank you very much it hepls, but now i see errors like this

`Error creating bean with name 'bedSecurityService': Unsatisfied dependency expressed through field 'bedManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bedManager': Unsatisfied dependency expressed through field 'biologicalDataItemManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'biologicalDataItemManager': Unsatisfied dependency expressed through field 'biologicalDataItemDao'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'biologicalDataItemDao': Unsatisfied dependency expressed through field 'daoHelper'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'daoHelper' defined in class path resource [conf/catgenome/dao/dao-helper.xml]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'listIdSequenceName' of bean class [com.epam.catgenome.dao.DaoHelper]: Bean property 'listIdSequenceName' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?`

Are there any suggestions, what caused it?

**Comment by sidoruka** [comment]
@Sanwel thanks for checking.
We'll look into it and fix by the end of this week.

**Comment by mzueva** [comment]
@Sanwel There we several issues regarding PostgreSQL deployment, we've merged the fix today. Could you please try the latest develop build?

**Comment by sidoruka** [comment]
As usual, built distributions are available as:
* jar: [dev/2.6.0.1340.1](http://ngb.opensource.epam.com/distr/dev/2.6.0.1340.1/)
* docker: `lifescience/ngb:2.6.0.1340.1-dev`

**Comment by Sanwel** [comment]
@mzueva thank you very much current version work fine with PSQL!
