### ISSUE TITLE
NGB does not load unregistered files.

### ISSUE THREAD

**Issue by Nikita-Privalov** [epam/NGB#299]
While trying to open NGB, we are getting nothing in the Registered Files section. In the console we have various JS-errors.
![ngb-081319-01](https://user-images.githubusercontent.com/28388083/62949156-5ce6b380-bdee-11e9-963b-dd2321103899.PNG)
![ngb-081319-02-02](https://user-images.githubusercontent.com/28388083/62949180-65d78500-bdee-11e9-9bc6-0f693883c454.PNG)

**Comment by sidoruka** [comment]
@Nikita-Privalov shall be fixed via #300 

Could you please check the latest version?
* jar: [dev/2.6.0.1350.1](http://ngb.opensource.epam.com/distr/dev/2.6.0.1350.1/)
* docker: `lifescience/ngb:2.6.0.1350.1-dev`

**Comment by Nikita-Privalov** [comment]
The issue is fixed. Thank you=)
