### ISSUE TITLE
Loading a structural variant vcf file manually into NGB doesn't display fusion genes

### ISSUE THREAD

**Issue by mjafin** [epam/NGB#3]
Hi there,
If I load a structural variant vcf file using the GUI it seems like the fusion genes do not get recognised. What is shown is `no affected gene` for both.

**Comment by sidoruka** [comment]
@mjafin , that looks like a network issue, NGB server is unable to access external databases that are used to retrieve details on genes  (transcripts/exons/domains). I will check and provide you a feedback shortly.

**Comment by sidoruka** [comment]
@mjafin , that is indeed caused by network connectivity issues. If NGB runs on a machine that requires proxy settings - they shall be set to a JVM environment, e.g.
`java -Dhttp.proxyHost=[proxy-ip] -Dhttp.proxyPort=[proxy-port] -jar catgenome.jar`

Please let me know if this fixes your problem

**Comment by mjafin** [comment]
You're right, it works now, thanks!
