### ISSUE TITLE
Show vertical line through all tracks.

### ISSUE THREAD

**Issue by Dmitrii-Romanov** [epam/NGB#30]
Add a vertical line which illustrates the centre of the visualized region on each track (not only on BAM). 
It will be useful in cases of compare some tracks. Its very helpful to see if peak summits line up on WIGs tracks.

**Comment by sidoruka** [comment]
Regarding the implementation, there are several points to consider:

1. Move "Show central line" option to **General** tab of **Settings** (see mockups below)
2. When it is checked (by default - checked) - central line, that is currently used only for BAM, shall be shown on other tracks

Current state:
![cl_prev](https://user-images.githubusercontent.com/20998291/29625504-93f6ff52-8834-11e7-9021-dd0ab8fee7ba.png)

TODO:
![cl_new](https://user-images.githubusercontent.com/20998291/29625493-8ea47656-8834-11e7-8830-24da29116631.png)
