### ISSUE TITLE
Error in case when user is loading .bw file and selecting chromosome for which data in .bw is not represented.

### ISSUE THREAD

**Issue by vpolyakov88** [epam/NGB#33]
1. register .bw file, in this file should be absent data for one or more chromosome
2. add this file in dataset
3. open dataset
4. open browser console
5. select chromosome which absent in .bw
expected: no errors, load indicator is disappearing during seconds
actual: load indicator isn't disappearing.
error in console
`{"message":"Parameter specified as non-null is null: method org.jetbrains.bio.big.BigFile.summarize, parameter name","status":"ERROR"}`
see server log file
[ngb_server_log.txt](https://github.com/epam/NGB/files/1235265/ngb_server_log.txt)

**Comment by sidoruka** [comment]
Here is an example of such behaviour:
[SV_Sample_1](http://52.38.214.1/catgenome/#/GRCh38/GL000008.2/1/209709?tracks=%5B%7B%22b%22:%22GRCh38%22,%22p%22:%22SV_Sample1%22,%22f%22:%22REFERENCE%22,%22h%22:20,%22s%22:%7B%7D%7D,%7B%22b%22:%22sv_sample_1.bw%22,%22p%22:%22SV_Sample1%22,%22s%22:%7B%22cls%22:false,%22csm%22:%22default%22%7D,%22h%22:50,%22n%22:%22sv_sample_1.bw%22,%22f%22:%22WIG%22%7D%5D)
