### ISSUE TITLE
Support for the narrowPeak and broadPeak

### ISSUE THREAD

**Issue by sidoruka** [epam/NGB#356]
There are two file formats, that we shall support in the NGB:
* [narrowPeak](http://genome.ucsc.edu/FAQ/FAQformat.html#format12)
* [broadPeak](http://genome.ucsc.edu/FAQ/FAQformat.html#format13)

In general, they are "BED-compatible", with some additional columns. Ideally, we'd like to:
* Be able to register them with the corresponding extension (`.narrowPeak` and `.broadPeak`)
* They shall be handled (by the server and the GUI) in the same manner as BED
* All the additional columns (3/4 columns of the corresponding format) shall be displayed in the tooltip in GUI, when hovering a feature

**Comment by maryvictol** [comment]
Files with extension .narrowPeak, .nPk, broadPeak, bPk have been registered correctly.

*Problems:*
1. For all BED-compatible files the starting position of the feature in the chromosome is  shifted 1 to the right
2. 'Score' value from file isn't displayed in the tooltip. Score is always displayed as 0.

**Comment by maryvictol** [comment]
Verified: Default value for 'Score' is shown in tooltip correctly
