### ISSUE TITLE
NGB GENE UNIPROT tab: 'No Data Available'

### ISSUE THREAD

**Issue by NadiraGaliamova** [epam/NGB#371]
Steps to reproduce:

1. Click on Transcript in the 'GENE' section (GRCh37.RefSeqGenes.UTR GeneralTranscript View: Collapsed);
2. Choose 'Show Info';
3. Click on the 'UNIPROT' tab.

Expected Result: The data is available.

Actual Result: 'No Data Available. Unexpected HTTP status: 301 Moved Permanently for URL http://www.uniprot.org/uniprot/?query=ENSG00000001626&format=xml'.

![uat2](https://user-images.githubusercontent.com/64957299/107215269-265a1b00-6a1c-11eb-8cf5-eb88b10ea3aa.png)
![uat](https://user-images.githubusercontent.com/64957299/107215275-26f2b180-6a1c-11eb-877c-83a55d4d1787.png)
![igt](https://user-images.githubusercontent.com/64957299/107215277-278b4800-6a1c-11eb-9249-7f4a9cce14b3.png)

**Comment by sidoruka** [comment]
Same as #283
* Fixed by bf34121
* Binaries are available here [2.6.0.2175](https://ngb-oss-builds.s3.amazonaws.com/web/index.html?prefix=public/builds/develop/2.6.0.2175/)

@NadiraGaliamova feel free to reopen the issue if the fix does not help
