### ISSUE TITLE
"Open from URL" allows to open only VCF and BAM files

### ISSUE THREAD

**Issue by sidoruka** [epam/NGB#39]
Currently "Open from URL" menu allows to open only VCF and BAM files.

If we try to open BED/GFF/GTF files - **LOAD** button is grayed out and does not allow to load that file.

![obu_disabled](https://user-images.githubusercontent.com/20998291/29625757-4d93b522-8835-11e7-953f-1709a3633057.png)

Seems that this bug is just a client-side check for vcf/bam files. So the list of supported files shall be extended to all other files extensions, that are supported by server. @mzueva could you please provide such a list?

**Comment by mzueva** [comment]
@sidoruka @ekoltsova 
Formats, that support browsing via URL:
- BAM
- BED
- GFF/GTF
- VCF

**Comment by sidoruka** [comment]
Some samples to test:
GTF:
* http://ngb.opensource.epam.com/distr/data/genome/dm6/dmel-all-r6.06.sorted.gtf.gz
* http://ngb.opensource.epam.com/distr/data/genome/dm6/dmel-all-r6.06.sorted.gtf.gz.tbi

GFF:
* http://ngb.opensource.epam.com/distr/data/genome/grch38/Homo_sapiens.GRCh38.gff3.gz
* http://ngb.opensource.epam.com/distr/data/genome/grch38/Homo_sapiens.GRCh38.gff3.gz.tbi

VCF:
* http://ngb.opensource.epam.com/distr/data/demo/ngb_demo_data/sample_1-lumpy.vcf.gz
* http://ngb.opensource.epam.com/distr/data/demo/ngb_demo_data/sample_1-lumpy.vcf.gz.tbi

BAM:
* http://ngb.opensource.epam.com/distr/data/demo/ngb_demo_data/PIK3CA-E545K.bam
* http://ngb.opensource.epam.com/distr/data/demo/ngb_demo_data/PIK3CA-E545K.bam.bai

CRAM:
* http://ngb.opensource.epam.com/distr/data/demo/ngb_demo_data/PIK3CA-E545K.cram
* http://ngb.opensource.epam.com/distr/data/demo/ngb_demo_data/PIK3CA-E545K.cram.crai

BED:
* http://ngb.opensource.epam.com/distr/data/genome/grch38/Homo_sapiens.GRCh38.domains.bed.gz
* http://ngb.opensource.epam.com/distr/data/genome/grch38/Homo_sapiens.GRCh38.domains.bed.gz.tbi
