### ISSUE TITLE
Impossible to save profiles with wrong conditions on Settings window 

### ISSUE THREAD

**Issue by Tatyana2022** [epam/NGB#399]
**Describe the bug**
Impossible to save profiles with wrong conditions on VCF tab of Settings window (#391 )

**Preconditions**
In the **interest_profiles.json** contains **'Crash'** profile with wrong condition:
`"Crash": {
 "is_default": false,
    "conditions": [
      {
        "highlight_color": "ffff00",
        "condition": "An = 5"
      },
      {
        "highlight_color": "008000",
        "condition": "Fs > 96.900"
      }
]
}
}`

**To Reproduce**
1. Go to 'NGB'
2. Go to 'Settings' 
3. Go to 'VCF' tab
4. Set checkbox in 'Enabled' field (if it is not set)
5. Select 'Crash' profile with wrong condition in dropdown list of 'select the profile' field
4. Click 'Save' button

**Expected behavior**
The profile with wrong condition should be saved successfully. 
'Settings' window is closed and  error conditions are ignored when highlighting variants
There is should be a warning  in the console indicating an error

**Actual behavior**
The profile with wrong condition is not saved and 'Settings' window is not closed.
Displays error in the console

**Screenshots**
![image](https://user-images.githubusercontent.com/83421565/118237348-e6358900-b49f-11eb-9088-b3d87912fdd0.png)

**Environment:**
 - NGB Version: 2.6.1.2293
 - Browser: Chrome (90.0.4430.93)

**Comment by rodichenko** [comment]
@Tatyana2022 #400 should fix this bug, could you re-check please?

**Comment by Tatyana2022** [comment]
Checked. Bug fixed
