### ISSUE TITLE
Conditions don't work if the Info field contains 'in' in the name of field

### ISSUE THREAD

**Issue by Tatyana2022** [epam/NGB#406]
**Describe the bug**
Conditions don't work if the Info field contains 'in' in the name of field (e.g. ClippingRankSum) (#391 )

**Prerequisites**
 - dataset = dm6_data, .vcf = agnts3.09-28.trim.dm606.realign.vcf
 -  **Different conditions (green highlight)** profile in interest_profiles.json file:
 `"Different conditions (green highlight)": {
  "is_default": true,
    "conditions": [
            {
        "highlight_color": "008000",
        "condition": "ClippingRankSum  == -0.982"
      },
      {
        "highlight_color": "ff0000",
        "condition": "MQ  == 91.95"
      }
]
},`

**To Reproduce**
1. Go to 'NGB'
2. Go to **Datasets** tab
3. Select dataset and vcf file from **Prerequisites**
4. Find Variation on Position  **chr X:12585943**
5. Click on found variation
6. Look at variation on vcf track in Browser

**Expected behavior**
Variation on Position  **chr X:12585943** should be highlighted in **008000 (green)** color since this color matches the first condition 

**Actual behavior**
Variation is highlighted in **ff0000 (red)** color that matches the second condition.  The first condition did not work

**Screenshots**
![image](https://user-images.githubusercontent.com/83421565/118646414-d93ecf80-b7e8-11eb-86e1-c67874464f40.png)

**Environment:**
 - NGB version: 2.6.1.2300
 - Browser: Chrome (version 90.0.4430.93)
 
**Additional context**
_**This behavior will be relevant for all info-fields that contain **'in**' in the name**(e.g. ClippingRankSum)_

**Comment by rodichenko** [comment]
@Tatyana2022 should be fixed with 3750adabefddb0968fccdc83bddf931d92ada6f1, could you re-check please?

**Comment by Tatyana2022** [comment]
Checked. Bug fixed

**Comment by Tatyana2022** [comment]
Checked. Bug fixed
