### ISSUE TITLE
Missing 'Show 3D structure' in context menu and empty 'Sequence' block for exons only

### ISSUE THREAD

**Issue by Tatyana2022** [epam/NGB#416]
**Describe the bug**
Missing 'Show 3D structure' in context menu and empty sequence block for exons only

dataset = **Felis_catus**, .bam = **SRR5373742-10m.bam**, .gtf = **Felis_catus.Felis_catus_9.0.94.sorted.gtf**

**To Reproduce**
1. Go to 'NGB'
2. Go to **Datasets** tab
3. Select dataset and bam file from **Prerequisites**
4. Go to Coordinates and search input control at right of tab's header
5. Set **BRCA2** in the **TYPE COORDINATES** 
6. Go to **GENE** track
7. Set **Expanded** view
7. Click on any exon on track 
8. Click on **Show info** in the context menu
9. Look at **Sequence** block in the **Feature info** modal window

**Expected behavior**
7.**Show info** and **Show 3D structure** should be displayed in the context menu
9. **Sequence** block should be filled by transcript sequence if user clicks on exon(e.g. GAAATTGTCCAAAGATAGTTACCTCTCATAGG...)

**Actual behavior**
7.**Show info** displays in the context menu. **Show 3D structure** isn't display in the context menu
9. **Sequence** block is blank in the **Feature info** modal window

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/83421565/120312998-1c696a00-c2e2-11eb-86ec-99d07fe50ecf.png)
![Screenshot_3](https://user-images.githubusercontent.com/83421565/120313007-20958780-c2e2-11eb-83d3-d3a7c6d3f8fe.png)
![image](https://user-images.githubusercontent.com/83421565/120313122-3f941980-c2e2-11eb-9643-d8ddb3320235.png)

**Environment:**
 - NGB version: 2.6.1.2352
 - Browser: Chrome (version 90.0.4430.212)

**Comment by rodichenko** [comment]
@Tatyana2022 d8efe2df3ac2e1fe9948014ecf3b69600d4dbda5 should fix this issue. We're displaying *transcript* sequence if user clicks on *exon*

**Comment by Tatyana2022** [comment]
Bug is checked and closed
