### ISSUE TITLE
BLAST - Get sequence coordinates for NCBI databases

### ISSUE THREAD

**Issue by mzueva** [epam/NGB#445]
**Background**
For in-house BLAST databases created from reference files BLAST returns alignment coordinates matching references registered in NGB. For NCBI databases BLAST returns alignment coordinated for NCBI sequences, e.g.
- nucleotide sequence [XM_019839322.2](https://www.ncbi.nlm.nih.gov/nucleotide/XM_019839322.2?report=genbank&log$=nuclalign&blast_rank=1&RID=CN0WKHVK013) 
- protein sequence [XP_003737221.1](https://www.ncbi.nlm.nih.gov/protein/XP_003737221.1?report=genbank&log$=protalign&blast_rank=1&RID=CN10X5RF016)

NGB server shall provide a new API method `GET blast/coordinates` with `sequenceId` and `type` [`PROTEIN`/`NUCLEOTIDE`] parameters. This method shall fetch sequence annotation from NCBI and try to find sequence coordinates, e.g. by gene or transcript name/id.

**Comment by SilinPavel** [comment]
should be resolved with https://github.com/epam/NGB/pull/456
