### ISSUE TITLE
BUG: Pagination is not reset to the first page when sorting by any column in the VARIANTS table

### ISSUE THREAD

**Issue by Tatyana2022** [epam/NGB#482]

**Comment by Tatyana2022** [comment]
To Reproduce:

1. Go to NGB
2. Go to 'Datasets' panel
3. Select any dataset with .vcf files (e.g. Fruitfly) 
4. Go to **Variants** panel 
5. Go to any page in the pagination (e.g. **4**)
6. Apply sorting to any column
7. Look at Pagination

***Expected result***
Sorting is applied. Pagination should be reset to the first page
***Actual result***
Sorting is applied. Pagination remained on the same page (**4**)

***Screenshot:***
![image](https://user-images.githubusercontent.com/83421565/125420414-41339e07-5eeb-41fa-8015-acc0a2ff5030.png)


Environment:

NGB version: 2.6.1.2562
Browser: Chrome Version 91.0.4472.114

**Comment by rodichenko** [comment]
@Tatyana2022 should be fixed by #630

**Comment by Tatyana2022** [comment]
***Verified***
