### ISSUE TITLE
BUG: Incorrect display of pages in pagination  when scrolling up in the Variants table

### ISSUE THREAD

**Issue by Tatyana2022** [epam/NGB#488]

**Comment by Tatyana2022** [comment]
To Reproduce:

1. Go to NGB
2. Go to 'Datasets' panel
3. Select any dataset with .vcf files (e.g. Fruitfly) 
4. Go to **Variants** panel 
5. Scroll down to the last page (6) 
6. Scroll up to the first page
7. Look at Pagination

***Expected result***
 First page should be underlined on the pagination. 
 
***Actual result***
 The last page (6) is underlined on the pagination.

***Screenshot:***
![image](https://user-images.githubusercontent.com/83421565/125821432-c1a91563-5041-40ac-999c-30edf98d6e3e.png)

***Extra details***
If you scroll to a page between 1 and 6 and stop, then the underline of the desired page will be loaded

Environment:

NGB version: 2.6.1.2579
Browser: Chrome Version 91.0.4472.114

**Comment by rodichenko** [comment]
@Tatyana2022 should be fixed by #630

**Comment by Tatyana2022** [comment]
***Verified***
