### ISSUE TITLE
BUG: An error displays in the console by opening .BAM file in the track

### ISSUE THREAD

**Issue by Tatyana2022** [epam/NGB#491]
**Preconditions:**
1. Open NGB
2. Open Console (F12)

**To Reproduce**

1. Go to 'Datasets' panel
2. Select  SV_Sample1 dataset with .bam file
3. Choose any Chromosome (e.g. CHR: 1)
4. Look at Console

**Expected behavior**
BAM file is displayed in the track. No errors in the console

**Actual result**
BAM file is displayed in the track
The following error displays in the console: 
`Uncaught TypeError: Cannot read property 'container' of null
    at BamRenderer.value (app.bundle.js:453)
    at BAMTrack.value (app.bundle.js:335)
    at BAMTrack.value (app.bundle.js:450)
    at dispatch (app.bundle.js:25)
    at elemData.handle (app.bundle.js:25)`

**Environment:**
 - NGB version: 2.6.1.2585
 - Browser: Chrome Version 91.0.4472.114

**Comment by rodichenko** [comment]
@Tatyana2022 #491 should fix that

**Comment by Tatyana2022** [comment]
Thanks @rodichenko 
***Bug is fixed and verified***
