### ISSUE TITLE
Performance issues on a configuration with thousands of genomes

### ISSUE THREAD

**Issue by sidoruka** [epam/NGB#5]
Having the following configuration:
1. ~50k genomes registered
2. ~100k datasets/files registered for the genomes above

Each NGB load takes unacceptable amount of time to load datasets tree, stats are below:
1. Versions used: 
1.1 2.4.2, 2.5.0 (pre-release)
1.2 Distribution used: Spring boot jar
2. Hardware:
2.1 CPU: 1 core
2.2 RAM: 2 Gb
3. Request used: load 2 tracks from a dataset, with a filtered datasets tree (`&filterByGenome=`)
4. Timings of the network requests series is below:

 Request                                 	| Time (sec) 	| Comment |
-----------------------------------------	|------------	|------------	|
 `/`                                       	| 3.84       	| *This is a static content request. The same data is served by nginx in ~100ms* |
 `/restapi/reference/loadAll`              	| 5.52       	| *Two identical `loadAll` calls. With smaller datasets - only one call is issued. Bug* |
 `/restapi/project/tree?referenceName=XXX` 	| 2.02       	| |
 `/restapi/reference/loadAll`              	| 3.46       	| *See previous `loadAll` comment* |
 **Total**                                   	| **14.84**      	| |

5. Having these stats, the following conclusions can be made:
5.1.  (HIGH) Double `loadAll` for the large datasets lists - fix: shall be only one call
5.2.  (HIGH) Do we really need to load all genomes? Shall fix to load only needed genomes
5.3.  (HIGH) Fine-tune springboot configuration for better static content serving
5.4.  (MED) Single dataset filter takes 2 seconds, which does not look reasonable - shall be optimized

6. Datasets - related issues shall be fixed in `hotfix/datasets-performance`

7. TODO:
* @rodichenko , 5.1 and 5.2 are for you to check
* @mzueva , please look into 5.3, 5.4

**Comment by rodichenko** [comment]
5.1 is fixed in 4cf107fcb2786b5c2c3bf842e2d69a95fd1d3260
Second request was sent because _references_ cache was empty (first request was still processing). That situation is prevented: if a request is in progress, we won't send another one

**Comment by rodichenko** [comment]
As for 5.2, it will take ~2 days. We will remove _references_ cache (all _datasets_ have reference track attached)

**Comment by mzueva** [comment]
5.4 /restapi/project/tree?referenceName=XXX should take about 300-400 ms in current version
5.3 needs further research, I think we need one more day to workout a solution

**Comment by sidoruka** [comment]
Thanks everyone, I've checked it. Here are the benchamaring results on the same datasets and hardware:

 Request                                 	| Time (sec) 	| Comment |
-----------------------------------------	|------------	|------------	|
 `/`                                       	| 0.004       	| *When local cache is used* |
 `/restapi/reference/loadAll`              	| 3.01       	| *This timing shall be reduced when 5.2 is done* |
 `/restapi/project/tree?referenceName=XXX` 	| 1.32       	| |
 `/restapi/reference/loadAll`              	| 0       	| *Second call is eliminated* |
 **Total**                                   	| **4.33**      	| |

Almost 10 seconds faster! Great!

Seems that we shall:
- Implement 5.2 (by filtering `loadAll` response by a selected genome name)
- Research 5.3 a bit deeper to handle first requests faster (cache is fine now)
- Optimize `tree?referenceName=XXX` request a bit (probably it can be faster by 0.5 - 0.7 seconds)

**Comment by sidoruka** [comment]
Looks like all issues are fixed.
Benchmarks are as follows:

 Request                                 	| Time (sec) 	| Comment |
-----------------------------------------	|------------	|------------	|
 `/`                                       	| 0.004       	| *All requests except very first request to the NGB instance* |
 `/restapi/reference/loadAll`              	| 0.8       	|  |
 `/restapi/project/tree?referenceName=XXX` 	| 1.06       	| |
 `/restapi/reference/loadAll`              	| 0       	| *Second call is eliminated* |
 **Total**                                   	| **1.86**      	| |

Looks good!
I'll leave this issue opened until 2.5 version is released

**Comment by sidoruka** [comment]
Closing this issue, as it seems to work fine in the specified environment. Version is tagged as v2.4.2 f4983b4
