### ISSUE TITLE
BUG: "BLASTp search" button is inactive and has different name in the context menu for some types in GENES panel

### ISSUE THREAD

**Issue by Tatyana2022** [epam/NGB#514]

**Comment by Tatyana2022** [comment]
**To Reproduce:**

1. Go to NGB
2. Select **SV_Sample1** dataset in **DATASETS** panel
2. Go to **GENES** panel
3. Open context menu for any row with **cds** type
4. Look at **BLASTp search** button

***Expected result***
 Clickable **BLASTp search** button should be displayed in the context menu 

***Actual result***
**Not** clickable button with different name (**BLASTp search Feature name is missing**) displays in the context menu

***Screenshot:***
![image](https://user-images.githubusercontent.com/83421565/128173201-a4b3025e-f6b3-43e9-8fce-f8b3daeabbfb.png)

**Extra details:**
The same behavior for the following types:
- selenocysteine
 - cds  
 - stop_codon  
 - 5utr  
 - start_codon
 - 3utr
 
**Environment:**
NGB version: 2.6.1.2639
Browser: Chrome Version 92.0.4515.107

**Comment by Tatyana2022** [comment]
@ZMaratovna  **Only GENE, MRNA or CDS Feature Type are supported** message is no longer displayed for all types except exon.

**Comment by rodichenko** [comment]
> @ZMaratovna **Only GENE, MRNA or CDS Feature Type are supported** message is no longer displayed for all types except exon.

@Tatyana2022 fixed by #606

**Comment by Tatyana2022** [comment]
***Verified***
