### ISSUE TITLE
Still low performance when loading large VCF into "Variations table"

### ISSUE THREAD

**Issue by sidoruka** [epam/NGB#54]
We still observe low performance while loading large vcf files (same files are used as in #16)

It takes up to 10 seconds to load variations tables without any filters.
3+ simulteneous requests cause NGB to hang.

**Comment by sidoruka** [comment]
TODO list:

At first fix shall be performed to `2.4-LTS` version

@rodichenko 
1. Fix double call to `searchGenes` API (when variations table is loaded)
2. Genes search behavior shall be changed:
* Do not request all genes at var table load time
* Request genes using `reference/{id}/search` API when user starts to enter gene's name (at least 2 letters shall be printed to start search)
* Other GUI features shall be left same (e.g. checkboxes, multiselect, etc.)
3. Once @mzueva finishes with `next-current-previous` page pointer - is shall be stored together with page number and be sent to the server when requesting previous/next page

@mzueva 
In addition to the optimizations:
1. Implement #45 in this issue
2. Once `2.4-LTS` is fixed and tested (@vpolyakov88 ping) - merge fixes to `develop`

**Comment by vpolyakov88** [comment]
It would be nice if user can set range filter only if chromosome or type of variation is selected. In other cases this filter shall be disabled.
