### ISSUE TITLE
NGB server shall throw 503 if it is overloaded instead of trying to fulfil request

### ISSUE THREAD

**Issue by sidoruka** [epam/NGB#55]
When NGB receives too many "huge" requests, it tries to fulfil them all. This results into loss of reponsiveness for minutes/hours for all users.

We shall introduce timeouts for the API methods. If a request can not be fulfilled in a certain amount of time - `HTTP 503` shall be returned.

Also a number of APIs shall not be wrapped with timeouts, such as registration API.

Let's begin from the most computation intensive methods, that are listed below. Once those are done and working, we can proceed with others.
* `/filter`
* `/filter/group`
* `/reference/loadAll`
* `/project/tree`
* `/bam/track/get`
* `/gene/{id}/track/get`
* `/wig/track/get`
* `/vcf/track/get`

Timeout setting shall be defined in `.properties` with default value `10 sec`

This feature shall be introduced in both `2.4-LTS` and current development branch `develop`

**Comment by sidoruka** [comment]
Linked to #54

**Comment by ainikolaev2013** [comment]
It seems to me that this issue is about introduction of API time outs.
Would the next steps be implementation of independence between the calls for various users or some kind of query queue prioritization?

**Comment by sidoruka** [comment]
This feature is implemented for certain cases when NGB is overloaded with requests, and a last chance to survive is reject some of them. 
We do not have plans for queue prioritization at the moment. Do not see any criteria for it. Do you have any suggestions? If so - please feel free to open new issue, we'll be happy to have a discussion on it.

**Comment by sidoruka** [comment]
Closing this issue, as the feature is implemented and merged
