### ISSUE TITLE
BUG: Feature graphics are displayed incorrect for BED files containing only 3 columns

### ISSUE THREAD

**Issue by maryvictol** [epam/NGB#557]
**Describe the bug**
Feature graphics are displayed incorrect and jumps during horizontal scrolling for BED files containing only 3 required columns.

**To Reproduce**
1. Go to NGB
2. Open **Twist_Exome_Target_hg38.bed** track 
3. Select any chromosome and position (for ex. CHR1 1: 74564432 - 80993668)
4. Scroll track horizontally

**Expected behavior**
Feature graphics should be displayed corresponding Start/End Indexes and should not layered on the feature count.

**Screenshots**
![image](https://user-images.githubusercontent.com/47791878/131342466-a3265237-fc4f-45f8-8a7d-b8401cf7f86e.png)

On the screenshot below you can see tracks for the same files with additional information and without it (only 3 columns):
![image](https://user-images.githubusercontent.com/47791878/131341148-3bfd2f47-7246-4df4-ab1d-10d2f776abb3.png)

**Environment:**
NGB version: 2.6.1 (localhost)
Browser: Chrome Version 92.0.4515.159

**Comment by Tatyana2022** [comment]
Verified
