### ISSUE TITLE
Add Expand symbol to annotation field in variation info

### ISSUE THREAD

**Issue by GennadiyZakharov** [epam/NGB#56]
At the moment on the variation info windows ANN field is collapsed by default and can be expanded by click. But visually this ability is not emphasized. 
I suggest adding some symbol that indicates that ANN field is expandable. The '+' or arrow down should be fine.
![ngb-annotation](https://user-images.githubusercontent.com/5824560/30068866-ba104c24-9267-11e7-8fb2-4abac9831438.png)

**Comment by sidoruka** [comment]
To be honest, there is "Exapnd/Collapse" indicator already
![ann_1](https://user-images.githubusercontent.com/20998291/30101836-6fc6f2a0-92f6-11e7-9f0c-09d832ae7670.png)

But I agree that it is not easy to figure it out for the first time. Especially using a wide monitor.
We shall probably move the indicator to left, so it will be easier to find

e.g.:
![ann_2](https://user-images.githubusercontent.com/20998291/30101903-a566e118-92f6-11e7-8cb4-4211f706b43b.png)
