### ISSUE TITLE
BUG:"Save" button is disabled for all settings tabs if there are no profiles for variations

### ISSUE THREAD

**Issue by Tatyana2022** [epam/NGB#560]
**Preconditions:**
No values in **interest_profiles.json** file

**To Reproduce**

1. Go to 'NGB'
2. Open **Settings** in left menu
3. Go to **VCF** tab
4. Go to any tab (e.g. General)

**Expected behavior**
**Save** button should be enabled for all tabs

**Actual behavior**
 **Save** button is disabled for all tabs
![image](https://user-images.githubusercontent.com/83421565/131665342-ced4f40a-0c7f-4229-a6b0-f36d5b8f0135.png)

**Environment:**
 -  NGB Version: 2.6.1.1(production)
 - Browser: Chrome (92.0.4515.159)

**Comment by mzueva** [comment]
Cannot reproduce
