### ISSUE TITLE
Automatic downloading of variation info from dbSNP

### ISSUE THREAD

**Issue by GennadiyZakharov** [epam/NGB#57]
If the variation has rsID we can get information about variation from dbSNP
(http://www.ncbi.nlm.nih.gov/projects/SNP/):

Here is a response example for variation rs7412:
Human-readable: http://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=7412   
XML: http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=snp&id=7412 
Detailed XML: http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=snp&id=7412&report=XML
JSON: http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=snp&id=7412&retmode=json
Clinvar JSON: http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=clinvar&id=7412&retmode=json

I suggest that for variation with rsID NGB should have Variation ID as a web-link to dbSNP and a separate info tab "dbSNP" (similar to "NCBI" and "Ensembl" tabs for genes. On clicking on this tab NGB should download and display the following information:
 1. Organism
 2. Map to Genome Build
 3. Variation Class: <Item Name="SNP_CLASS"
 4. RefSNP Alleles: 
 5. Clinical Significance: <Item Name="CLINICAL_SIGNIFICANCE"
 6. MAF/MinorAlleleCount
 7. MAF Source:	
 8. HGVS Names: <Item Name="DOCSUM"
 9. From table with variation location (Primary Assembly Mapping ):
 a) Assembly (reference name)
 b) Chr
 c) Chr Pos
 d) Contig
 e) Contig Pos
 10. From table RefSeq Gene Mapping:
 a) RefSeqGene
 b) Gene (ID)

**Comment by sidoruka** [comment]
@nkarulin , please implement appropriate connectivity mechanism on a server-side (same technique as other databases, but I believe there is already some draft implementation for dbSNP integration)

@ekoltsova , GUI part goes to you. Seems that @GennadiyZakharov provided enough details, if there are any more questions - please refer to him.

**Comment by sidoruka** [comment]
**1. Organism - no**
 2. Map to Genome Build - ok (genomeLabel)
 3. Variation Class - ok (snp_class)
 **4. RefSNP Alleles - no**
 5. Clinical Significance - ok (clinical_significance)
 **6. MAF/MinorAlleleCount - no**
 **7. MAF Source - no (same as previous)**
 8. HGVS Names ok (docsum - semicolon divided)
 9. From table with variation location (Primary Assembly Mapping)
 a) Assembly (reference name) - ok (genomeLabel)
 b) Chr - ok (chr)
 c) Chr Pos - ok (chrpos)
 d) Contig - ok (contigLabel)
 e) Contig Pos - ok (contigpos)
 10. From table RefSeq Gene Mapping:
 **a) RefSeqGene - no**
 b) Gene (ID) - ok (genes->name, genes->gene_id)

**Comment by SilinPavel** [comment]
@sidoruka 
I found out that with method `catgenome/restapi/externaldb/ncbi/variation/{rsId}/get` we can get all what we need.
So there is mapping 1,4,6,7,10(a):
1. Organism -  organism_summary
4. RefSNP Alleles -  refsnp_alleles
6. MAF/MinorAlleleCount - global_maf
7. MAF Source - maf_source
10(a). RefSeqGene - ref_seq_gene

**Comment by sidoruka** [comment]
@TimSPb89 
Additional requirement:
Add a `ClinVar` link if a variation is `pathogenic`.

**Comment by TimSPb89** [comment]
@SilinPavel 
Don't get MAF/MinorAlleleCount (global_maf) from the server

**Comment by SilinPavel** [comment]
So there is pull request (#79) from @TimSPb89, but some issue was leaved to the next version:
- NCBI Rest API does not provide information about MAF from ExAC base (https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=snp&id=12729295&retmode=json), but it's available on https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=12729295 we should find a way to get it from NCBI Rest API or may be we should implement interaction with ExAC rest API.
- **SNP to RefSeqGene** column from RefSeqGene Mapping (https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=12729295) should be added to our response

**Comment by sidoruka** [comment]
Closing this issue, as most of the functionality is implented in #79 
Remaining features will be moved to the subsequent versions
