### ISSUE TITLE
BUG: "Incorrect application behavior when pressing the S button while the molecular viewer is open"

### ISSUE THREAD

**Issue by Tatyana2022** [epam/NGB#570]
**To Reproduce**

1. Go to 'NGB'
2. Select **SV_Sample1** dataset in DATASETS panel
3. Open **GENES** panel from VIEWS menu
4. Filter panel by **kras** name
5. RIght click bu **kras** gene
6. Click **Show 3D structure** button in context menu
7. Go to Chr coordinates in Browser
8. Enter the letter **S** in coordinates using keyboard

**Expected behavior**
1) The letter **S** should be entered in coordinates of Browser. 
2) The contrast of the molecule shouldn't change when press the **S** button on the keyboard

**Actual behavior**
1) The letter **S** is not entered in coordinates. Can't enter into any text field (e.g. Genes edit mode) 
2) The contrast of the molecule changes by pressing the **S** key on the keyboard.

**Screenshots:**
<img src="https://user-images.githubusercontent.com/83421565/132292613-e3d6193d-7b0c-4bf6-a4ca-d7a5d2bd649d.png" width="200" /> <img src="https://user-images.githubusercontent.com/83421565/132292652-f4372321-dd4e-42d8-b2d7-384a0334b08b.png" width="200" />

**Environment:**
 -  NGB Version: 2.6.1.2797
 - Browser: Chrome (92.0.4515.159)

**Comment by rodichenko** [comment]
@Tatyana2022 65483fe659f65a7b5163c32b38b17aa381230f1b should fix that

**Comment by Tatyana2022** [comment]
Verified
