### ISSUE TITLE
Extend allowed location formats

### ISSUE THREAD

**Issue by GennadiyZakharov** [epam/NGB#58]
Implement sevaral possible coordinate formats for location:
**Implemented ones:**
`chromosome:start-end` 
`chromosome:location` - place center of the screen to location

**Suggested ones:**
`chromosome:` - navidate to the whole chromosome (minimum )
`start-end` - navigate to region on current chromosome (only if chromosome already selected)
`location` - - place center of the screen to location on current chromosome

**Comment by sidoruka** [comment]
We shall probably be able to use tabs as a delimiter
