### ISSUE TITLE
BUG: No context menu for files with Feature_Counts label

### ISSUE THREAD

**Issue by Tatyana2022** [epam/NGB#601]
To Reproduce:

1. Go to NGB
2. Go to 'Datasets' panel
3. Select **sv_sample_1.byGTF.featureCounts** file in  **SV_Sample1** dataset 
4. Go to **BROWSER** panel
5. Set **12: 25200174 - 25255550** coordinates in Browser header
6. Go to **Feature_Counts** track 
7. Set **Features** value in **Display** view (if not set)
8. Click on any exon/feature

***Expected result***
Context menu should be displayed for features
 
***Actual result***
The context menu does not appear for features

**Extra Details**
The same behavior for all files with Feature_Counts label

Environment:

NGB version: 2.6.1.2889
Browser: Chrome Version 93.0.4577.82

**Comment by rodichenko** [comment]
@Tatyana2022 fixed by #610

**Comment by Tatyana2022** [comment]
***Verified***
