### ISSUE TITLE
BUG: The tooltip expands to the length of the value inside

### ISSUE THREAD

**Issue by Tatyana2022** [epam/NGB#607]
To Reproduce:

1. Go to NGB
2. Go to 'Datasets' panel
3. Select  file with long values in context menu in  any dataset 
4. Navigate to any gene in the track

***Expected result***
Tooltip with very long values should be clipped and display ellipsis
 
***Actual result***
Tooltip expands to the length of the value inside

Environment:

NGB version: 2.6.1.2889
Browser: Chrome Version 93.0.4577.82

**Comment by rodichenko** [comment]
@Tatyana2022 styles fixed by #609

**Comment by Tatyana2022** [comment]
***Verified***
