### ISSUE TITLE
Allow to customize BLAST options inputs

### ISSUE THREAD

**Issue by mzueva** [epam/NGB#612]
**Background**
At the moment user has two ways to specify BLAST options: `Max target sequences` and `Expected threshold` inputs and `Options` string for all other options. For some cases it would be helpful to customize which options to show as separate inputs.

![image](https://user-images.githubusercontent.com/12640002/134359364-92fbd51b-798c-44bd-8892-54831c9b70a7.png)

**Approach**
Allow to configure options inputs via `blast_settings` in `defaultTrackSettings`, e.g.:
```
{
   "evalue": 0.05,
   "options": {
        "max_target_sequence": {
            "name": "Max target sequences",
            "defaultValue": 100,
            "minValue": 1,
            "type": "integer"
         },
         "num_threads": {
            "name": "Expected threshold", 
            "defaultValue": 0.5,
            "type": "double",
            "minValue": 0
            "maxValue": 1
         }
    }
}  
 ```
- options shall be passed as option string `-key value`
- key shall be used as option name
- all fields are optional
- `name` shall be used as input label

**Comment by rodichenko** [comment]
@mzueva implemented by fa447be4d90f56d05bea63ee020643b22b7eb3bd
