### ISSUE TITLE
BUG: Datasets not displaying after reapplying search to dataset panel

### ISSUE THREAD

**Issue by Tatyana2022** [epam/NGB#619]
**To Reproduce**

1. Go to 'Datasets' panel
2. Select any dataset (e.g. **sv_sample1**)
3. Go to Search field at the top of the DATASETS panel
4. Apply any search (e.g. 2) 
5. Restart the search
6. Look at results in DATASETS panel

**Expected behavior**
The DATASET's panel should display all datasets and files matching the search value. Matching values should be highlighted

**Actual result**
1) Datasets are collapsed
2) There are no dataset names in the panel
3) Matching values are not highlighted

![image](https://user-images.githubusercontent.com/83421565/134593030-6b665e67-01de-4cbb-bb10-711f538230d9.png)

**Environment:**
 - NGB version: 2.6.1.2933
 - Browser: Chrome Version 94.0.4606.54

**Comment by rodichenko** [comment]
@Tatyana2022 #626 should fix that

**Comment by Tatyana2022** [comment]
***Verified***
