### ISSUE TITLE
BUG: Variants graphs collapsed to the left of the visual blocks in the Browser panel 

### ISSUE THREAD

**Issue by Tatyana2022** [epam/NGB#622]
**To Reproduce**

1. Go to 'Datasets' panel
2. Select **SV_Sample2** dataset 
3. Select any file in **SV_Sample1** dataset (e.g. sv_sample_1.bam)
4. Unselect chosen file (e.g. sv_sample_1.bam)
5. Look at Variants graphs in **Browser** panel

**Expected behavior**
Variants graphs should be displayed depending on the values in selected .vcf files

**Actual result**
Variants graphs collapsed to the left of the visual blocks in the Browser panel 
<img src="https://user-images.githubusercontent.com/83421565/134660526-b44980f1-11fc-45ce-a270-7b8aa54e55f6.png" width="200" />

**Environment:**
 - NGB version: 2.6.1.2934
 - Browser: Chrome Version 94.0.4606.54

**Comment by rodichenko** [comment]
@Tatyana2022 should be fixed by #628

**Comment by Tatyana2022** [comment]
***Verified***
