### ISSUE TITLE
BUG: Description is displayed as response from Network

### ISSUE THREAD

**Issue by Tatyana2022** [epam/NGB#656]
**To Reproduce**

1. Open NGB
2. Go to **DATASETS** menu
3. Select **SV_Sample1** dataset
4. Look at **BROWSER** panel

**Expected behavior**
Description view should be displayed in the Browser panel (if exists) 

**Actual result**
The response from the network is displayed instead of the file with the description

**Extra Details:**
Summary view should be displayed in the BROWSER header and panel, if there is no Description file in Dataset

**Screenshots:** 
<img src="https://user-images.githubusercontent.com/83421565/137112806-13329453-2c12-4dde-a5f8-a27fdb8373a2.png" width="200" />

**Environment:**
 - NGB version: 2.6.1.3053
 - Browser: Chrome Version 94.0.4606.71

**Comment by rodichenko** [comment]
@Tatyana2022 should be fixed with b525079db6373dad2156c42f9ada006137740d85

**Comment by Tatyana2022** [comment]
***Fixed and Verified***
