### ISSUE TITLE
BUG: A space appears after the highlighted search match in file names in the dataset tree.

### ISSUE THREAD

**Issue by Tatyana2022** [epam/NGB#666]
**To Reproduce**

1. Open NGB
2. Go to **DATASETS** panel
3. Enter any value in search field (e.d. te)
4. Look at search result in the dataset tree

**Expected behavior**
All search matches should be highlighted without spaces after in the word

**Actual result**
Matches for the searched value is highlighted.
Displays a space after matched value in the word. (e.g. Te st)
This behavior is relevant for files only 

**Screenshots:** 
<img src="https://user-images.githubusercontent.com/83421565/137454331-1912ceb1-5919-4548-b04a-c5eeebf0adae.png" width="200" />

**Environment:**
 - NGB version: 2.6.1.3063
 - Browser: Chrome Version 94.0.4606.81

**Comment by rodichenko** [comment]
@Tatyana2022 should be fixed by 650e500cc2af495296e69543d3cec4710d86b4d9

**Comment by Tatyana2022** [comment]
***Verified***
