### ISSUE TITLE
[BLAST] Improve navigation to BLAST results

### ISSUE THREAD

**Issue by mzueva** [epam/NGB#667]
**Background**
Let's improve navigation options for BLAST results for `CUSTOM` databases:
- Allow to associate BLAST database with a specific reference. If `referenceId` is specified for a database it shall be used for navigation instead of `taxid`
- For some cases more than one reference can match `taxid` in this cases we should allow user to select a reference from the list for navigation.
- For custom databases support sequence notation `reference:chromosome`, e.g. `hg38:chr1`

**Comment by rodichenko** [comment]
@mzueva implemented by #671
