### ISSUE TITLE
BUG: Unable to view read info for plain users

### ISSUE THREAD

**Issue by mzueva** [epam/NGB#675]
**Describe the bug**

**To Reproduce**
1. Login as non-admin user
2. Select BAM track and go to reads
3. Click on any read and observe that read info is not loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/12640002/138101157-b7b8b206-92d8-4a21-bfdc-9760b34b5a21.png)

**Additional context**
Error is caused by `Access denied` as client doesn't set `projectId` for `/bam/read/load` request body.

**Comment by Tatyana2022** [comment]
***Fixed and verified***
