### ISSUE TITLE
Split view via unified coordinates and search control

### ISSUE THREAD

**Issue by NShaforostov** [epam/NGB#706]
**Background**

Currently, NGB supports split view for the Browser panel, e.g. to open mate regions of pair alignments or show pair for inter-chromosomal variants.
It could be convenient to expand this functionality and allow users to split browser for any location of interest - via the unified coordinates and search control.

**Approach**

- Add the support of specifying two pairs of coordinates in the unified coordinates and search control:
  - in this case, user will specify two pairs of coordinates separated by space to the coordinates field and confirm the input by the Enter key. After that, a second browser pane should be opened - in the main pane, the first specified location should be displayed, in the second pane - the second location (_similar behavior to the current split view_), e.g.:
  ![image](https://user-images.githubusercontent.com/45459424/145382081-23572e39-9a5e-4711-afe5-0ac5f5a9c23c.png)
  ![image](https://user-images.githubusercontent.com/45459424/145382874-e9640724-7607-41b3-b905-caee00249881.png)
  - shall be supported the following formats for each location:
    - "coordinates" formats:  
      - `<COORDINATE>` - the location shall be opened on the current chromosome and have the specified coordinate as central position
      - `<START_COORDINATE>-<FINISH_COORDINATE>` - the location shall be opened on the current chromosome and have the specified coordinates as location boundaries
      - `<CHR_NAME>:<COORDINATE>` - the location shall be opened on the specified chromosome and have the specified coordinate as central position
      - `<CHR_NAME>:<START_COORDINATE>-<FINISH_COORDINATE>` - the location shall be opened on the specified chromosome and have the specified coordinates as location boundaries
    - "feature" formats:
      - `<FEATURE_NAME>` - a gene, transcript, feature name. Shall be opened the first location from search result list
    - locations can be separated by any count of spaces
  - the unified coordinates and search control in the additional browser pane shall be disabled to changing (_same behavior to the current split view_). If user will change location in the "main" browser pane - this location shall be opened in the "main" browser pane and the additional browser pane (split view) shall be closed
  - the additional browser pane shall have only "**Expand**" and "**Close**" buttons
- Add the ability to open a first location from the search results list by Enter-press - when searching location by the name in the unified coordinates and search control, e.g.:
  ![image](https://user-images.githubusercontent.com/45459424/145387076-1b61e1ff-d607-4016-a115-ed4a4e0d40c8.png)
  If user will press Enter in this case - the `KRAS gene` shall be opened.
  The ability to open manually a certain item from the list - by click it - shall remain as previously.

**Comment by Tatyana2022** [comment]
**Bug was found:**
Enter button does not work with "<COORDINATE.>" and "<CHR_NAME>:<START_COORDINATE>-<FINISH_COORDINATE>" format

**Steps to reproduce:**
1. Go to NGB
2. Go to DATASETS panel
3. Select **SV_Sample2** dataset
4. Go to BROWSER panel
5. Select **4** chromosome in dropdown menu
6. Set following coordinates in the field: 25665006 4:49096-50124
7. Click **Enter** button on keyboard

**Expected result:**
2 BROWSER panels are opened.  
1)CHR4: 25665006 should be displayed in the main panel 
2) CHR4:49096-50124 should be displayed in the second panel 

**Actual result:**
**Enter** button is not active

**Extra Details:**
The same behavior for coordinates where <FEATURE_NAME>  entered first
@mzueva @rodichenko 

***Verified***

**Comment by Tatyana2022** [comment]
**Bug was found:**
Positions are not displayed with the following coordinate input format: "<COORDINATE.>" and "<COORDINATE.>"

**Steps to reproduce:**
1. Go to NGB
2. Go to DATASETS panel
3. Select **SV_Sample2** dataset
4. Go to BROWSER panel
5. Select **4** chromosome in dropdown menu
6. Set following coordinates in the field: **25665006 25665003**
7. Click **Enter** button on keyboard

**Expected result:**
2 BROWSER panels are opened.  
1)CHR4 should be displayed with position 25665006 
2) CHR4 should be displayed in the second panel  with position 25665003*

**Actual result:**
Сoordinates are displayed for the entire length of the chromosome

**Extra details:**
The same behavior for:
 <CHR_NAME>:<COORDINATE> and <COORDINATE.>
 <CHR_NAME>:<COORDINATE> and  <CHR_NAME>:<COORDINATE>
<CHR_NAME>:<COORDINATE> and <CHR_NAME>:<START_COORDINATE>-<FINISH_COORDINATE>

 
@mzueva @rodichenko 
***Verified***

**Comment by rodichenko** [comment]
> **Bug was found:** Enter button does not work with "<COORDINATE.>" and "<CHR_NAME>:<START_COORDINATE>-<FINISH_COORDINATE>" format

> **Bug was found:** Positions are not displayed with the following coordinate input format: "<COORDINATE.>" and "<COORDINATE.>"
> 

@Tatyana2022 should be fixed with 6f8ce02081ee06bca9db103fc36748a6b69ca6a0

**Comment by NShaforostov** [comment]
Docs were added via #724 and located [here](https://github.com/epam/NGB/blob/develop/docs/md/user-guide/tracks.md#split-view).
