### ISSUE TITLE
Ability to configure the visibility of Browser pane controls for using in iFrame

### ISSUE THREAD

**Issue by NShaforostov** [epam/NGB#707]
**Background**

Currently, when the Browser NGB pane is used in `iFrame` elements - all pane controls are being displayed the same as in "regular" mode. It may confuse users in some cases, e.g. user can click the cross button on the pane - this will close all tracks, pane header but the element itself (`iFrame`) will be still shown as empty gray-filled rectangular.
To avoid such cases, we should add the ability to configure the visibility of the Browser pane controls.

**Approach**
* Add the parameter to control the visibility of the Browser pane controls:
![image](https://user-images.githubusercontent.com/20998291/145807859-ba6188c9-1287-4c60-8292-ff2e0db3bae9.png)
* It shall be possible to:
  * Hide any of these controls (one or several in a row)
  * Hide all of these control (via single parameter)
* The following embedding options shall support this new parameter:
  * [URL parameters](https://github.com/epam/NGB/blob/develop/docs/md/user-guide/embedding-url.md)
  * [JS API](https://github.com/epam/NGB/blob/develop/docs/md/user-guide/embedding-js.md)
* Make sure to update the `embedding` documents (see previous point) with the new parameters description

**Comment by rodichenko** [comment]
@NShaforostov @sidoruka @mzueva #712 implements **JS API** methods and **url parameters** for hiding panels controls.

## URL parameters
`embedded` and `controls` options were added to the url:
- `embedded`: string (values: `on`/`off`) - turns *on* or *off* the "embedded" mode (if set to `on`, all controls will be hidden; **close** button for the single non-reference track will be hidden)
- `controls`: valid json string (i.e. `{"close": "off"}`) - turns on/off controls individually. See available keys below.

Note that "embedded" mode has highest priority - if it is set to "on", `controls` options are ignored.

## JS API methods
- `setEmbedded` method: accepts single parameter `embedded` (true / false) - to turn "embedded" mode on/off.
```js
window.postMessage({method: 'setEmbedded', params: {embedded: true}});
```
- `setControlsVisibility` method: turns on/off particular controls:
```js
window.postMessage({method: 'setControlsVisibility', params: {close: false, maximize: true, fit: false}});
```

## Control keys
- `close`: panel's *close* buttons;
- `maximize`: panel's *maximize* buttons;
- `fit`: *fit all tracks* button;
- `organize`: *organize tracks* button;
- `annotations`: *genome annotation files* button;
- `project`: *project info* button;
- `selection`: *tracks selection* button;
- `clear`: *close all tracks* button;
- `vcfcolumns` (lowercased!): specify VCF columns to display button;
- `vcfdownload` (lowercased!): *download variants table* button;
- `genesdownload` (lowercased!): *download genes table* button;
- `closelasttrack` or `closeLastTrack`: hide close button for the single non-reference track;
- `closelasttrackignoreformats` or `closeLastTrackIgnoreFormats` (array of strings, default: `['MOTIFS, 'BLAST']`): if `closeLastTrack` is set to `false`, specified track formats will be ignored, i.e. if there are 3 tracks - MOTIFS positive, MOTIFS negative, BAM - BAM track won't be closable

Note: for *URL parameters* user must specify *controls* visibility by setting values to `on` or `off` (i.e., `...controls={"vcfdownload":"off"}...`); for *JS API* methods user must provide *boolean* values (i.e., `...{vcfdownload: false}...`).

**Comment by NShaforostov** [comment]
Docs were added via #720 and located [here](https://github.com/epam/NGB/blob/develop/docs/md/user-guide/embedding-url.md#embedding-ngb-via-iframe-controlled-with-url) and [here](https://github.com/epam/NGB/blob/develop/docs/md/user-guide/embedding-js.md#setembedded).
