### ISSUE TITLE
Support sample aliases for VCF files

### ISSUE THREAD

**Issue by mzueva** [epam/NGB#727]
### Background
At the moment sample names are read from VCF file during registration and displayed on the GUI as-is. For some cases it would be useful to allow user to set some "user-friendly" aliases for sample names.

### Approach
- provide an API method to set sample alias for VCF file
- VCF file API methods returning sample names, shall return aliases map as well
- add the ability to set sample alias for multi-samples VCF tracks via the GUI

### Details
For the ability to rename samples, to the **General** menu of multi-samples VCF, the item "Rename samples" should be added:
![image](https://user-images.githubusercontent.com/45459424/152829853-6f56d143-6cdd-45e9-a4db-87fe18183556.png)

By click this item, a new pop-up shall appear:
![image](https://user-images.githubusercontent.com/45459424/152943992-cc3aa6f6-714f-4951-881a-e094f0961b17.png)

That pop-up shall contain:
- table with all sample names from the current multi-sample VCF:
  - column "_Sample_" shall contain origin sample names (as they were obtained during the VCF file registration). Each sample name should be represented as an immutable label
  - column "_Alias_" shall contain aliases for samples - a single alias for each sample. Each alias should be represented as a plain text in the text input field. By default, an alias field should be empty (_if the alias was not specified previously_)
- buttons to save or cancel changes

User shall have the ability to specify alias(es) for any sample(s) and click the **Save** button to confirm changes.
Herewith, there shall not be the ability to save the same alias for several samples.

After the saving, changes shall be being displayed at the multi-sample VCF track by the following rules:
- if a sample has an alias - this alias should be displayed
- if a sample doesn't have an alias - for that sample, its origin sample name should be displayed
![image](https://user-images.githubusercontent.com/45459424/152944917-37367a51-2aaf-4d4d-bdaf-58d099986d86.png)
![image](https://user-images.githubusercontent.com/45459424/152838592-fb43652a-4ffe-420b-a33d-53c27bf5618c.png)
**_Note_**: names/aliases should be being displayed in any "Variants view" according to described rules

Additionally, these rules shall be applied to sample names/aliases in the "Variants" table of the **Variants** panel:
![image](https://user-images.githubusercontent.com/45459424/152839579-e89be09b-7305-4247-a169-ac89ca1d679c.png)

#### Other options

The changing of samples' aliases shall be applied globally, i.e. if the user has set the aliases for some multi-sample VCF track - any other user, that has access to this VCF, should see these new sample aliases on the track and **Variants** table.

**Comment by NShaforostov** [comment]
Docs were added via #776 and located [here](https://github.com/epam/NGB/blob/develop/docs/md/user-guide/tracks-vcf.md#sample-aliases).
