### ISSUE TITLE
Visual glitch: Filesizes of megabyte magnitude are displayed as "bytes"

### ISSUE THREAD

**Issue by kay73** [epam/NGB#745]
**Describe the bug**
The files in the screenshot are actually Megabytes rather than bytes.

**Screenshots**
<img width="999" alt="Bildschirmfoto 2022-01-26 um 14 36 08" src="https://user-images.githubusercontent.com/10027056/151172870-b06d73a4-b8f1-4656-89e7-49172fda42d8.png">

**Environment:**
 - Catgenome Version commit: e10d008aec5b7889f01d4d62e0aaa1b50c1c7a97

**Comment by mzueva** [comment]
@kay73 Thank you for the issue, it shall be fixed in the latest `develop` build via 62ae424f4327d2c706d3fafb55ff35a0fe8a3f4f
