### ISSUE TITLE
Reference track double strand

### ISSUE THREAD

**Issue by Jemkon** [epam/NGB#75]
Hello,

Great tool..... Is it possible to add reverse strand to REFERENCE sequence? I would also like to add translation in first frame on forward sequence. 

Many thanks.

**Comment by sidoruka** [comment]
Hi @Jemkon , seems that this feature is currently in work within #50 .
PR #62 that implements it will be merged by the end of this week.

Is that what you were looking for?

**Comment by sidoruka** [comment]
PR is merged sometime ago, hope that helped.
