### ISSUE TITLE
cannot load Wheat genome

### ISSUE THREAD

**Issue by wangzwYYDS** [epam/NGB#838]
the full command ： 
ngb rr Genome/Triticum_aestivum.IWGSC.dna.toplevel.fa -n CS1.1 -t -m 100000

the full error :

11:42:26.773 [main] ERROR com.epam.ngb.cli.app.Application - Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space

the `docker stats ` situation ：

MEM USAGE / LIMIT
5.314GiB / 251.4GiB 

cannot reg_ref the wheat genome (21 chr , maybe 14Gb base)  ,  
installed the  NGB software on Centos DOcker 
The NGB software version : 2.7.1
tried `-m 100000`  , not  working

in additon, i use `docker stats` , to see the memory of NGB ,  the memory not full use.

how to solve the problem.

**Additional context**
The wheat bam file has *.bam.csi  index  , can NGB use it ? 

Poor english , thanks

**Comment by wangzwYYDS** [comment]
`ngb rr Genome/Triticum_aestivum.IWGSC.dna.toplevel.fa  -n wheat  -m 1000000  -ngc `  
 
solved. 

another problem is 

ngb rf wheat   Genome/sort.gtf -n wheat_gene -t
09:05:51.692 [main] ERROR com.epam.ngb.cli.manager.command.handler.http.FileRegistrationHandler - Your operation has been aborted due to NGB has encountered a server problem.
09:05:51.698 [main] ERROR com.epam.ngb.cli.manager.command.handler.http.FileRegistrationHandler - Failed to register files: Genome/sort.gtf.

and  ngb cannot recognize the csi index file 

ngb add wheat_data AFS.source.sort.bam?AFS.source.sort.bam.csi
09:23:19.172 [main] ERROR com.epam.ngb.cli.app.Application - Index file [AFS.source.sort.bam.csi] doesn't match file format [BAM].

**Comment by mzueva** [comment]
Hi @wangzwYYDS,
Could you please tell us, are you starting the NGB docker using the default command `docker run -p 8080:8080 -d --name ngbcore -v <YOUR_NGS_DATA_FOLDER>:/ngs ngb:latest`?

If that's the case, we have a limit for java memory of 2 gigabytes and it may be insufficient for large genomes. Could you please start docker container specifying launch command, giving 4 gigabytes or more using `-Xmx4G` flag, e.g:
```
docker run -p 8080:8080 -d --name ngbcore -v <YOUR_NGS_DATA_FOLDER>:/ngs ngb:latest /bin/bash -c  "cd /opt/ngb/ && java -Xmx4G -jar catgenome.jar"
```

**Comment by wangzwYYDS** [comment]
@mzueva 
thanks for your reply.
ngb version ==  2.7.1.3535  
`ngb rr Genome/Triticum_aestivum.IWGSC.dna.toplevel.fa  -n wheat  -m 1000000  -ngc `  could load wheat genome ,without error

 ngb cannot recognize the csi index file ?   
wheat has some chromosome is larger than 500Mb ,cannot  make index , cannot produce bai file

new samtools  could produce csi index file , could NGB recognize the csi index file ?   
I try
` ngb add wheat_data AFS.source.sort.bam?AFS.source.sort.bam.csi`
but failed.

09:23:19.172 [main] ERROR com.epam.ngb.cli.app.Application - Index file [AFS.source.sort.bam.csi] doesn't match file format [BAM].

**Comment by mzueva** [comment]
@wangzwYYDS Regarding CSI indices, unfortunately we are not supporting this format at the moment, only bai indices are supported. We'll consider this feature for further development.
