### ISSUE TITLE
Target Management

### ISSUE THREAD

**Issue by mzueva** [epam/NGB#847]
**Background**
Subtask for #839 
Target management implementation
Target object includes:
- `Name` - target name. Shall be shown as hyperlink. By click it, the target details form shall be opened
- `Disease` - a list of diseases that are associated with the target
- `Product` - a list of products (e.g. vaccines) that are associated with the target
- `Genes` - list of objects with fields `gene_name`, `gene_id`, `species_name`, `species_tax_id`, `priority`

API for:
- create new target
- modify target: add and delete genes
- delete target
- get list of targets with paging and filters:
  - text search by gene name
  - filters by gene_name, disease, products, species_name (multi-values OR), also a method to get all values for filters is required (same as for variations table)

**Comment by mzueva** [comment]
Let's improve API to filter and list targets:
- Add sorting option (field name + ASC/DESC)
- Allow to get available values for genes, species, diseases, product
- Search by name shall be simple string query without drop down/multiselect

**Comment by mzueva** [comment]
Priority handling:
- From GUI prospective let's change value to drop-down "High"-"Low"
- On the server side: let's switch to enum value for priority ["High", "Low"], but with associated numeric values, e.g. high = 100, low - 0, and still store in the database as int

**Comment by maryvictol** [comment]
**Bug:**
Attempt to Save target after update gives the error `Error updating target`.

---
Verified. Works well

**Comment by maryvictol** [comment]
**Bug:**
At creation targets from orthologs and paralogs Species are filled out incorrectly.

<img src="https://github.com/epam/NGB/assets/47791878/4b7c5d2d-dff7-47a1-957a-ee2886e2b48d"   width="600">
<img src="https://github.com/epam/NGB/assets/47791878/c2e8d452-6881-40b8-a20e-4eeb24b5efc5"   width="600">

---
Verified. Works correctly

**Comment by maryvictol** [comment]
@rodichenko 
Extra tooltips for `Diseases` and `Products` lines on the _Create/Edit Target_ form.
![image](https://github.com/epam/NGB/assets/47791878/06489d53-e85c-4209-bbc7-d5d26742130a)
![image](https://github.com/epam/NGB/assets/47791878/234e9eb7-0d73-4ccb-8154-fd18c6c8035c)

---
Verified. Works correctly

**Comment by maryvictol** [comment]
@rodichenko 
On the _Edit Target_ form **Save** button should be disabled if no changes are made.

---
Verified. Works correctly

**Comment by maryvictol** [comment]
@rodichenko 
**Bug:**
_Filter **Targets** table by gene:_ 
if the list of existing in the table genes contains names that differ only by case, then if you choose one of them and then any other gene, then the first selected gene becomes disabled to uncheck in the list.
**To reproduce:**
1. Open **Targets** table
2. Select _Show filters_ option
3. Click in the _Genes_ filter field
4. Select `BRCA1` gene. >> `brca1` gene is checked automatically
5. Select `BRCA2` gene. 
6. Try to uncheck `BRCA1` gene.

**Actual result:** `BRCA1` gene is disabled.

---
Verified. Works correctly
