### ISSUE TITLE
Launching target identification

### ISSUE THREAD

**Issue by mzueva** [epam/NGB#849]
**Background**
Subtask for #839

**Approach**
- Implement API method `POST /target/identification` with body, where species are specified using tax id:
```
{
  "targetId": 1L,
  "speciesOfInterest":  [ 9612 ],
  "translationalSpecies": [ 9606, 10090]
}
```
- Method shall return structure matching 6 identification blocks: 
```
  {
      "description": {},
      "knowDrugs": {},
      "sequences": {}.
      "comparativeGenomics": {},
      "structure": {},
      "bibliography": {} 
  }
```
- As a first step implement "description" section using following approach:
  - load target and filter genes by specified  `speciesOfInterest` and `translationalSpecies`
  - fetch from NCBI (similar approach or  reuse `NCBIGeneManager.fetchGeneById`) information for each gene, it would be great to fetch all genes at once and return `gene_summary ` field
  - format of response for description block, order of genes should match one specified in the request: 
 ```
    {
       "description": {
                "ENSG00000133703": "This gene, a Kirsten ras oncogene homolog from ....",
                 "ENS,,,,": "other description"
        },
        ...
     }
 ```

**Comment by mzueva** [comment]
Let's switch to gene based approach: pass target & translational geneIds as input for identification. 

![image](https://github.com/epam/NGB/assets/12640002/d9c91b69-c584-4e6e-a494-2dcff1a960a8)

**Comment by maryvictol** [comment]
@rodichenko 
**Bug:**
If any description is not found for target identification, then the short overview and summary description remain from the previous target identification if it has been launched.

**To Reproduce**
1. Launch identification process for _KRAS - KRAS proto-oncogene_ with `Interest: KRAS (Homo Sapiens), Translational: KRAS (Homo Sapiens)` 
2. Return to **Targets** table and repeat launching identification process for _PGLYRP4_ with `Interest: PGLYRP4 (Macaca mulatta), Translational: PGLYRP4 (Macaca mulatta)`

**Actual result:**
The short overview and summary description contain information from the first launch.

---
No longer relevant as the short overview has been removed from the design.

**Comment by maryvictol** [comment]
@mzueva, @rodichenko 
**Bug** :
If a description for the target exists in _NCBI_ but doesn't exist in _Open Targets Platform_, then the description isn't shown in the short overview (ex.: geneID -  `ensg00000106351`, Launch target `ArfGAP with FG repeats` with `Interest: agfg2 (Homo_sapiens), Translational: agfg2 (Homo_sapiens)` )
<img src="https://github.com/epam/NGB/assets/47791878/1e8c957a-e628-485a-95e0-68be3b415fad"   width="600">

---
No longer relevant as the short overview has been removed from the design.

**Comment by maryvictol** [comment]
@rodichenko 

Link _Show more/Show less_ shouldn't be shown if the Description is initially displayed in full.
**To reproduce:** Launch target `PGLYRP4` with `Interest: PGRP-SC1a (Drosophila melanogaster), Translational: PGRP-SC1a (Drosophila melanogaster)`
![image](https://github.com/epam/NGB/assets/47791878/57f02f3f-8c46-48d2-8dde-8e9b32c692f6)

![image](https://github.com/epam/NGB/assets/47791878/de17f07d-b10d-4a43-aae9-0b879c4ccabc)

**Comment by maryvictol** [comment]
@mzueva 
**Bug:**
If the target exists in _NCBI_ but doesn't exist in _Open Targets Platform_  launch identification process gives the error `For input string: ""`.
**To reproduce** launch identification process for `PGLYRP4` with `Interest: PGLYRP4 (Macaca mulatta), Translational: PGLYRP4 (Macaca mulatta)`

---
Verified. Works well.
