### ISSUE TITLE
[Target Identification] Disease & drugs panel

### ISSUE THREAD

**Issue by mzueva** [epam/NGB#865]
**Background**
Implementation according to #839

**Comment by mzueva** [comment]
Let's extend filtering and sorting options for new tables
`Drugs` - filtering and sorting by fields + get fields values method
`Diseases` - add sorting by score fields, default sorting by overall DESC, + sorting/search by disease name

**Comment by maryvictol** [comment]
@rodichenko 
Non-Latin letters are shown incorrectly in the **_Associated Diseases_** Table/Bubbles/Graph.
**For reproduce:**
_Target name_: C2CD5
_Launch parameters:_ Interest: C2CD5 (Homo sapiens), Translational: C2CD5 (Homo sapiens)
`Familial partial lipodystrophy, Köbberling type`  :
<img src="https://github.com/epam/NGB/assets/47791878/ff0494ef-4779-443b-ba16-98c85d5614bd"   width="450">

---
Verified. Non-Latin letters are shown correctly.

**Comment by maryvictol** [comment]
@rodichenko 
 **_Associated Diseases_** Table problems:
1. The arrow showing the sort direction isn't displayed in the columns with long headers.
2. The target is displayed twice in the _Target_ column filter drop-down if `Genes of Interest` and `Translational genes` match.
![image](https://github.com/epam/NGB/assets/47791878/83f88e6e-bc4e-42f0-aafc-3259282c2615)

--- 
Verified. Both points work well.

**Comment by maryvictol** [comment]
@mzueva 

**Bug:**
**Known Drugs** tab:  Filters by _**Interaction Claim Source**_  and _**Drug**_ don't return results.

---
Verified after reindexing

**Comment by maryvictol** [comment]
@okolesn 

Filter by _Drug_ in the **Known Drugs** tab and filter by _Disease_ in the **Associated diseases** tab don't return results if the search value contains a hyphen.
**For reproduce:** KRAS with Interest: kras (Homo_sapiens), Translational: krasp1 (Homo_sapiens)
**Associated diseases** : contains Disease `HIV-1 infection` but  filter  `"filters":[{"field":"DISEASE_NAME","terms":["HIV-1"]}]` returns `{"payload":{"totalCount":0},"status":"OK"}`.
The same result for filter _Drug_  by `MRTX-849` in the **Known Drugs** tab.
