### ISSUE TITLE
BLAT search

### ISSUE THREAD

**Issue by GennadiyZakharov** [epam/NGB#90]
[BLAT](https://en.wikipedia.org/wiki/BLAT_(bioinformatics)) is an annotation utility which allow user to efficiently search for a potential location of particular DNA sequence. UCSC provides web service for BLAT search.
IGV has ability to submit a prticular read sequence to BLAT and view results.

NGB should have the same functionality
By clicking on each read and selecting "BLAT sequence "user shold be able to send read sequence to BLAT. The search results should be displayed in additional popup window or tab, similar to IGV.
By clicking on the each line user can navigate to specified location (chromosome and position from start to end). 

The results of each BLAT search are represented in BLAT as a BED track, where each region is a potential location reported by BLAT.
I suggest that user should have and ability to hide BLAT results window/tab and show it again from results track.

**Comment by sidoruka** [comment]
@SilinPavel , please add API stub for BLAT search results, so @ekoltsova  and @TimSPb89 could proceed with GUI implementation

**Comment by sidoruka** [comment]
@ekoltsova @TimSPb89 
Once @SilinPavel will provide you API, the following GUI forms shall be implemented:
1. Add "BLAT Search" menu item to the alignment context menu

2. Once this item is clicked - request server API and visualize results in the table view
- Table view shall be opened as a separate tab (same look and feel as "Variants" tab)
- Tab shall be named "BLAT"
- Requests sequence shall be shown in the top of the panel
- Search results shall be shown below a sequence in the tableview
- This tab shall not be available to open from "Views" menu. It exists only for the session time

3. If user clicks a table row - NGB shall navigate to the specified region: `chr: start-end` (visible range shall be set as +/- 10% of `end - start`)

**Comment by SilinPavel** [comment]
@ekoltsova, @TimSPb89 
There is API: "/bam/read/blat?bamTrackId={bamTrackId}" + readSequence in the request body
For now it will always produce the same results:
`````
{
  "payload": [
    {
      "start": 111572177,
      "end": 111572278,
      "chr": "chr3",
      "match": 101,
      "misMatch": 0,
      "repMatch": 0,
      "qGapCount": 0,
      "tGapCount": 0,
      "ns": 0,
      "qGapBases": 0,
      "tGapBases": 0,
      "score": 1000,
      "strand": "NEGATIVE",
      "name": "mockedBlatSearchResult0"
    },
   ....
  ],
  "status": "OK"
}
`````
I believe that it will be enough for you.
This API method also check that reference contains "Species" - version of genome build and type of organism.
Contact me if you have any question!
