### ISSUE TITLE
[BUG] Unhandled exception in gene info

### ISSUE THREAD

**Issue by vpolyakov88** [epam/NGB#91]
1. select dataset that have indexed GTF/GFF3
2. find OR6K1P gene
3. click gene and click "Show info" point in appeared menu
4. go to "UNIPROT" tab
exp.: handlen and userfriendly error message
act.: see screenshot
![image](https://user-images.githubusercontent.com/14569208/31190316-6c25a8f4-a943-11e7-89a7-c0df9cfaf527.png)

**Comment by sidoruka** [comment]
@vpolyakov88 , could you please (for this and further issues) specify commit which was used for testing?
Currently I can not check this as I do not know what code you are using.

Also, what is your suggestion regarding the "correct" behaviour?

**Comment by sidoruka** [comment]
Closing a outdated
