### ISSUE TITLE
Show full file name on a track header

### ISSUE THREAD

**Issue by Dmitrii-Romanov** [epam/NGB#93]
File name is not fully displayed on a track header. It would be nice if users could see the full file name when they mouse over the bam file name.

**Comment by sidoruka** [comment]
I believe this is the example for this issue:
![cropped_name](https://user-images.githubusercontent.com/20998291/31505600-f0aa0332-af7d-11e7-8e75-72702f6f6a57.png)

@ekoltsova , could you please add a tooltip with a full file name when hovering it?
