### ISSUE TITLE
[Target Identification] Disease View

### ISSUE THREAD

**Issue by mzueva** [epam/NGB#959]
## Background

It would be helpful to add a separate tab to Target Identification panel allowing to search for diseases and view related information.

## Approach

A new tab **Diseases** in the [**Target identification**](#839) panel shall be added.
At this tab, there shall be abilities:
- to search for disease (case insensitive substring search)
- to view the following information for the found disease:
  - _Name_, _Synonyms_, _Description_
  - Associated drugs (as a table)
  - Associated targets (as a table with heatmap)

<hr/>

- [Search for disease](#search)
- [Disease info](#disease_info)
  - [Known drugs block](#drugs)
  - [Associated targets block](#targets)
- [Other options](#options)

<hr/>

<h3 id="search">Search for disease</h3>

By default, **Diseases** tab shall be empty and contain:
- Search input field - to specify the desired disease name
- **Search** button - to perform the search
![image](https://github.com/epam/NGB/assets/45459424/a293c005-54be-4f41-a190-478aedd6c287)

To start the search, user shall specify disease name or its part to the input field.
Search shall be case insensitive.
Search results shall appear in the Google-like manner - with appearing of suitable values during the disease name input - these values shall be suggested from [Open Targets](https://platform.opentargets.org/) diseases database, e.g.:
![image](https://github.com/epam/NGB/assets/45459424/6456e564-e907-431e-85ea-f9dbb23851e6)

User shall have abilities:
- to select one of the suggested found values by click it in the list, e.g.:
  ![image](https://github.com/epam/NGB/assets/45459424/28d2ad49-2af1-4dc6-b777-173215227074)
  In this case, results shall be output for the selected disease.
- to click the **Search** button. In this case, search results shall be output for the first found disease in the list of suitable ones. If nothing is found - the corresponding message shall appear.

<h3 id="disease_info">Disease info</h3>

Once the desired disease is found, the following form shall appear (in the same **Disease** tab):
![image](https://github.com/epam/NGB/assets/45459424/f5aec040-7826-4486-bf32-da817c87695d)

Form shall contain:
- search input field and the **Search** button - to perform another disease search
- disease info block:
  - label with the disease name
  - list of synonyms of the found disease
  - label with the disease description
- set of expandable sections. There shall be the following sections:
  - _Known drugs_ section - section with the information about drugs with investigational or approved indications for the current disease
  - _Associated targets_ section - section with the information about targets associated with the current disease

Below, there are details by each expandable block.

<h4 id="drugs">Known drugs block</h4>

Block shall contain:
- header with the number of found drugs
- table for investigational or approved drugs indicated for the current disease
- button to export the table content to the local workstation in CSV format
![image](https://github.com/epam/NGB/assets/45459424/84b1deb4-4065-42f6-8ac9-cbe763629cab)

Table shall include columns:

- _Disease_ - disease name (current disease or its synonym) treated by the drug. Each disease shall be hyperlink to the corresponding page in [Open Targets](https://platform.opentargets.org/)
- drug details columns:
  - _Drug_ - drug name. Each drug shall be hyperlink to the corresponding page in [Open Targets](https://platform.opentargets.org/)
  - _Type_ - drug type (antibody, cell, enzyme, molecule, protein, etc.)
  - _Mechanism of action_ - drug action to the target (includes action type and target name)
  - _Action type_ - drug action type
- target info columns:
  - _Target_ - symbol of the associated target
  - _Target name_ - name of the associated target
- clinical trials info columns:
  - _Phase_ - current stage of a clinical trial studying a drug
  - _Status_ - state of the current clinical trial phase
  - _Source_ - hyperlink to the corresponding page of the clinical trial

By default, table shall be sorted by the _Disease_ column.
Table shall support:
- sorting by any column
- filtering by any column
- paging

<h4 id="targets">Associated targets block</h4>

Block shall contain:
- header with the number of found associated targets
- table for targets associated with the current disease
- button to export the table content to the local workstation in CSV format
![image](https://github.com/epam/NGB/assets/45459424/95365f44-d45a-42bf-b2f9-02245364da8e)

Table shall include columns:

- _Target_ - symbol of the associated target
- _Target name_ - name of the associated target
- _Overall score_ - summary score of all disease-target association scores
- other columns - specific disease-target association scores. For more details see [here](https://platform-docs.opentargets.org/associations).

Table shall be colorized as a heatmap - according to the score value in each cell.
By default, table shall be sorted by the _Overall score_ column.
Table shall support:
- sorting by any column
- paging
- filtering by columns _Target_, _Target name_

<h3 id="options">Other options</h3>

There shall be the ability to open described disease view from the [Target Identification results](https://github.com/epam/NGB/issues/839#view_identification) - from the **Associated diseases** section.
To open disease view, user shall open the context menu for the desired disease in the **Associated diseases** table and click the corresponding item, e.g.:
![image](https://github.com/epam/NGB/assets/45459424/50eb91c2-64f1-447f-afb9-a0b337db5ec4)

By click that item, the tab **Diseases** of the **Target identification** panel shall be opened with the info about selected disease.

**Comment by maryvictol** [comment]
@mzueva 

The number of found **drugs** (**_Known Drugs_** tab) and **targets** (**_Associated targets_** tab) aren't shown in the header of the corresponding tabs.

---
Verified as fixed

**Comment by maryvictol** [comment]
@rodichenko 

**Bugs with Filters:***
**Known Drugs** tab:
- _Mechanism Of Action_ and _Action Type_ columns: in the filter search values drop-down checkboxes for values with commas aren't ticked at selection (for ex.  Disease `non-small cell lung carcinoma`, filter by `3',5'-cyclic phosphodiesterase inhibitor`)
![image](https://github.com/epam/NGB/assets/47791878/9fc926ad-aa37-40bc-a88f-366ac7374d67)

- For all columns with filter's drop-down:  drop-down is hidden under the **Associated targets** tab header for tables with a small number of records.
![image](https://github.com/epam/NGB/assets/47791878/8a1f4e52-25b3-4f0f-9913-1f381febfd50)

---
Verified as fixed

**Comment by maryvictol** [comment]
@mzueva 

**Bug:**
***Known Drugs*** tab : Sort by _Target Name_ gives error:
`unexpected docvalues type NONE for field 'GENE_NAME' (expected=SORTED). Re-index with correct docvalues type.`

---
Verified as fixed

**Comment by maryvictol** [comment]
@mzueva 

**Bug:**
***Known Drugs*** tab : Filter _Mechanism Of Action_ and _Action Type columns_ by values containing `[ ]` gives error:
`Cannot parse 'Poly [ADP-ribose] polymerase-1 inhibitor': Encountered \" \"]\" \"] \"\" at line 1, column 16.\nWas expecting:\n    \"TO\" ...`

---
Verified as fixed

**Comment by maryvictol** [comment]
@mzueva 

**Bug:**
***Known Drugs*** tab : Filters with drop-down list  (_Mechanism Of Action_, _Action Type columns_,  etc.) should filter tab by the entire selected value, and not by the occurrence of each word from it.
